### ISSUE TITLE
Crafting Table Crash with Magical Crops Item

### ISSUE THREAD

**Issue by JustJinxed** [Vazkii/Botania#1101]
When placing a Accio Sword (from Magical Crops) in a crafting table alone, I'm getting an error. Not sure if it's due to the old RegenIvy bug from way back, of if this is a Magical Crops issue? Client doesn't error if I place something else in the grid first, only if the sword is alone. 

Figure I'd run it by you guys first since I recall seeing this sort of behavior last year with items from tinker's construct and some isRepairable flag issues. 
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/17/15 12:51 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 42
	at net.minecraft.item.Item$ToolMaterial.func_150995_f(Item.java:1390)
	at net.minecraft.item.Item$ToolMaterial.getRepairItemStack(Item.java:1413)
	at net.minecraft.item.ItemSword.func_82789_a(ItemSword.java:104)
	at vazkii.botania.common.crafting.recipe.RegenIvyRecipe.func_77569_a(RegenIvyRecipe.java:46)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:53)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.Item$ToolMaterial.func_150995_f(Item.java:1390)
	at net.minecraft.item.Item$ToolMaterial.getRepairItemStack(Item.java:1413)
	at net.minecraft.item.ItemSword.func_82789_a(ItemSword.java:104)
	at vazkii.botania.common.crafting.recipe.RegenIvyRecipe.func_77569_a(RegenIvyRecipe.java:46)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:53)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

Full Log: http://pastebin.com/riqNZtYR

**Comment by Vazkii** [comment]
This is in fact the same issue from a while back with Mekanism and Mine&Blade.

**Comment by DrZed** [comment]
Wow, I still have this issue... I just crashed 3 times trying to craft a damn tier 2 tool...

**Comment by yrsegal** [comment]
![mtg-threadnecromancer_3198](https://cloud.githubusercontent.com/assets/6596492/16902690/70f28ee6-4c34-11e6-8428-22a97201f54a.jpg)

**Comment by DrZed** [comment]
I love it, 10/10. I was hoping Vazkii did it though, knowing the MTG references in his mod.

**Comment by yrsegal** [comment]
Vazkii isn't the only person who plays Magic ._.

**Comment by DrZed** [comment]
I Bypassed the crash and still crafted my pick using a hilarious workaround...
I used optifine (denies OpenGL crashes) and used the Translocators crafting on ground thing and input recipe and crafted the tool.

Lol, I know, BTW I was named after MTG (My real name is Keldon (Keldon Warlord) I have near-mint white border version of it lel)

**Comment by yrsegal** [comment]
White border? You monster.
Also optifine will break your everything, don't expect it to work out.

**Comment by DrZed** [comment]
I hate people like you, who automatically assumes optifine = bad. I got news for you, I've used it in every modpack I've had, FTB Infinity Evolved Skyblock Expert mode recently, and several others. Only crappily made code crashes with optifine, Only 1 bug I've found in any modern mod, Chisel some of it's terribly coded connected texture blocks render invisibly. Only people who do not understand how to use optifine have problems, I've spoken to the author of the mod on many occasions, and he knows what he's doing when he made the mod the issue with certain mods was their crappily handled render code that was half-assed, There is a reason FastCraft's author player recommends using the mod on his page for fastcraft.

**Comment by williewillus** [comment]
Stop bickering and either report the issue to my repo if it's on 1.9 or stop necroing a by now completely irrelevant issue

**Comment by DrZed** [comment]
It's not irrelevant since still over 60% of the community uses 1.7.10 still.

**Comment by JRoffel** [comment]
It IS irrelevant, because the support for the 1.7.10 version of botania has ended, no matter what the community uses.

**Comment by DrZed** [comment]
I hate people who ignore their users, there is a thing called "The customer is always right"
The consumers of the product consume a product they like, not what the producer wants them to use. (unless it's Apple) Hence why I still update 1.7.10, 1.8.9, 1.9.4, and 1.10.0

**Comment by yrsegal** [comment]
@Vazkii please lock this, it's going nowhere fast ._.

**Comment by williewillus** [comment]
@yrsegal you were part of the problem
@DrZed yes except we aren't businesses. 1.7 version is inactive and that's that.

**Comment by gigaherz** [comment]
Lol sorry to butt in, but I had to say: @DrZed, a customer is someone who paid money to receive the product. When you use something that's free, you are not the customer, you are either the product (user data for market analysis and/or targetted advertising), or the facilitator of that product (the ad views/clicks themselves). You may not want to accept this, but you have no right to demand anything. Be glad for all the things that DO work, they are entertainment that you got for ***free***.
