### ISSUE TITLE
Flügel tiara / baubles crash

### ISSUE THREAD

**Issue by Hyxaru** [Vazkii/Botania#1271]
Equip Flügel tiara, get:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 18-8-15 19:02
Description: Ticking entity

java.lang.NoClassDefFoundError: codechicken/lib/vec/Vector3
	at vazkii.botania.common.item.equipment.bauble.ItemFlightTiara.onWornTick(ItemFlightTiara.java:176)
	at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at vazkii.botania.common.item.equipment.bauble.ItemFlightTiara.onWornTick(ItemFlightTiara.java:176)
	at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_9_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 219
	Entity Name: Hyxaru
	Entity's Exact location: 157,64, 82,90, 248,27
	Entity's Block location: World: (157,82,248), Chunk: (at 13,5,8 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Hyxaru'/219, l='MpServer', x=157,64, y=82,90, z=248,27]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (140,64,256), Chunk: (at 12,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1409 game time, 1409 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntitySkeleton['Skeleton'/2056, l='MpServer', x=216,78, y=32,00, z=211,38], EntityWolf['Wolf'/77, l='MpServer', x=76,50, y=68,40, z=257,50], EntitySkeleton['Skeleton'/2638, l='MpServer', x=191,50, y=20,00, z=270,50], EntityWolf['Wolf'/80, l='MpServer', x=76,50, y=66,40, z=263,50], EntityWolf['Wolf'/83, l='MpServer', x=83,50, y=64,00, z=311,50], EntityWolf['Wolf'/84, l='MpServer', x=81,31, y=64,00, z=292,78], EntityWolf['Wolf'/109, l='MpServer', x=116,50, y=67,00, z=229,50], EntityWolf['Wolf'/110, l='MpServer', x=118,50, y=66,00, z=230,50], EntityWolf['Wolf'/111, l='MpServer', x=117,50, y=66,00, z=228,50], EntityWolf['Wolf'/112, l='MpServer', x=116,63, y=68,00, z=221,66], EntityWolf['Wolf'/113, l='MpServer', x=110,59, y=72,00, z=247,69], EntityWolf['Wolf'/114, l='MpServer', x=105,22, y=73,00, z=264,69], EntityWolf['Wolf'/115, l='MpServer', x=104,25, y=73,00, z=264,50], EntityWolf['Wolf'/116, l='MpServer', x=109,66, y=69,00, z=271,31], EntitySheep['Sheep'/118, l='MpServer', x=105,19, y=67,00, z=278,06], EntityWolf['Wolf'/121, l='MpServer', x=112,28, y=69,00, z=298,06], EntityWolf['Wolf'/122, l='MpServer', x=105,59, y=64,00, z=295,97], EntityWolf['Wolf'/123, l='MpServer', x=109,59, y=63,00, z=296,84], EntityWolf['Wolf'/124, l='MpServer', x=103,44, y=67,00, z=277,09], EntityWolf['Wolf'/125, l='MpServer', x=122,28, y=66,00, z=304,34], EntityWolf['Wolf'/126, l='MpServer', x=115,50, y=64,00, z=298,50], EntityWolf['Wolf'/127, l='MpServer', x=119,50, y=65,00, z=296,50], EntityWolf['Wolf'/128, l='MpServer', x=117,50, y=64,00, z=301,50], EntityWolf['Wolf'/141, l='MpServer', x=125,53, y=68,00, z=178,03], EntityWolf['Wolf'/142, l='MpServer', x=131,50, y=61,40, z=174,50], EntityWolf['Wolf'/143, l='MpServer', x=131,56, y=61,40, z=175,44], EntityWolf['Wolf'/144, l='MpServer', x=130,34, y=64,00, z=177,66], EntityWolf['Wolf'/145, l='MpServer', x=120,69, y=73,00, z=280,50], EntityWolf['Wolf'/146, l='MpServer', x=126,50, y=72,00, z=284,50], EntityWolf['Wolf'/147, l='MpServer', x=136,06, y=77,00, z=290,69], EntityWolf['Wolf'/148, l='MpServer', x=129,78, y=76,00, z=286,31], EntityWolf['Wolf'/153, l='MpServer', x=183,47, y=85,00, z=253,88], EntityWolf['Wolf'/154, l='MpServer', x=187,66, y=82,00, z=258,50], EntityWolf['Wolf'/155, l='MpServer', x=188,53, y=87,00, z=256,94], EntityWolf['Wolf'/156, l='MpServer', x=184,28, y=80,00, z=252,44], EntityItem['item.tile.cloth.white'/4764, l='MpServer', x=204,13, y=89,13, z=253,63], EntityWolf['Wolf'/162, l='MpServer', x=196,75, y=68,00, z=206,00], EntityWolf['Wolf'/163, l='MpServer', x=194,66, y=68,00, z=198,69], EntityWolf['Wolf'/164, l='MpServer', x=194,50, y=68,00, z=206,50], EntityWolf['Wolf'/165, l='MpServer', x=194,50, y=68,00, z=205,50], EntityWolf['Wolf'/166, l='MpServer', x=185,50, y=70,00, z=218,50], EntityWolf['Wolf'/167, l='MpServer', x=184,50, y=70,00, z=218,50], EntityWolf['Wolf'/168, l='MpServer', x=188,50, y=69,00, z=218,50], EntityWolf['Wolf'/169, l='MpServer', x=184,50, y=70,00, z=218,50], EntityWolf['Wolf'/170, l='MpServer', x=197,50, y=72,00, z=315,50], EntityWolf['Wolf'/171, l='MpServer', x=185,94, y=69,00, z=319,69], EntityWolf['Wolf'/172, l='MpServer', x=186,47, y=65,40, z=322,94], EntityWolf['Wolf'/173, l='MpServer', x=194,50, y=66,40, z=321,50], EntitySkeleton['Skeleton'/2737, l='MpServer', x=137,50, y=18,00, z=262,50], EntityZombie['Zombie'/4786, l='MpServer', x=124,50, y=30,00, z=292,50], EntityZombie['Zombie'/4787, l='MpServer', x=126,50, y=30,00, z=294,50], EntityZombie['Zombie'/4788, l='MpServer', x=122,50, y=30,00, z=290,50], EntitySheep['Sheep'/182, l='MpServer', x=205,72, y=88,00, z=256,06], EntitySheep['Sheep'/185, l='MpServer', x=204,38, y=89,00, z=251,16], EntityWolf['Wolf'/191, l='MpServer', x=220,50, y=82,00, z=261,50], EntityWolf['Wolf'/192, l='MpServer', x=204,69, y=89,00, z=253,50], EntityWolf['Wolf'/194, l='MpServer', x=223,50, y=82,00, z=259,50], EntityZombie['Zombie'/4818, l='MpServer', x=203,50, y=25,00, z=316,50], EntityItem['item.tile.cloth.silver'/4840, l='MpServer', x=100,25, y=68,13, z=272,75], EntityClientPlayerMP['Hyxaru'/219, l='MpServer', x=157,64, y=82,90, z=248,27], EntitySkeleton['Skeleton'/4380, l='MpServer', x=116,28, y=45,00, z=275,31], EntityBat['Bat'/4416, l='MpServer', x=150,25, y=33,20, z=298,13], EntityBat['Bat'/4418, l='MpServer', x=148,78, y=32,70, z=298,13], EntityBat['Bat'/865, l='MpServer', x=207,16, y=17,04, z=246,34], EntityBat['Bat'/866, l='MpServer', x=212,41, y=23,98, z=239,09], EntityZombie['Zombie'/5015, l='MpServer', x=193,50, y=20,00, z=268,50], EntityBat['Bat'/409, l='MpServer', x=156,67, y=32,00, z=291,32], EntityZombie['Zombie'/2457, l='MpServer', x=150,50, y=29,00, z=296,50], EntityItem['item.tile.cloth.white'/4508, l='MpServer', x=205,16, y=87,13, z=256,63], EntityItem['item.tile.cloth.white'/4512, l='MpServer', x=108,06, y=69,13, z=271,59], EntityZombie['Zombie'/424, l='MpServer', x=76,50, y=13,37, z=292,50], EntityZombie['Zombie'/2515, l='MpServer', x=97,50, y=15,00, z=288,50], EntitySlime['Slime'/994, l='MpServer', x=213,22, y=39,00, z=200,22], EntityCreeper['Creeper'/493, l='MpServer', x=152,50, y=33,00, z=287,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 367674720 bytes (350 MB) / 535093248 bytes (510 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.7-210} [Botania] (Botania r1.7-210.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Vazkii** [comment]
._____________.
