### ISSUE TITLE
Botania and Progression incompitability

### ISSUE THREAD

**Issue by Katrix-** [Vazkii/Botania#1415]
Seems like Botania and Progression causes a crash when hitting another player with some weapons in Botania. The weapons I know this have happened with so far is the Star Caller and the Terra Blade, the could be others. Happened with build 221, but as far as I know, nothing has changed in this area for the new release.

Crash log:
Star Caller
```
java.lang.NullPointerException: Ticking entity
	at joshie.progression.criteria.triggers.TriggerKill.canIncrease(TriggerKill.java:47)
	at joshie.progression.criteria.triggers.TriggerBaseCounter.onFired(TriggerBaseCounter.java:29)
	at joshie.progression.player.CriteriaMappings.fireAllTriggers(CriteriaMappings.java:227)
	at joshie.progression.handlers.APIHandler.fireTrigger(APIHandler.java:53)
	at joshie.progression.handlers.APIHandler.fireTrigger(APIHandler.java:60)
	at joshie.progression.criteria.triggers.TriggerKill.onEvent(TriggerKill.java:29)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_689_TriggerKill_onEvent_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at vazkii.botania.common.entity.EntityFallingStar.onImpact(EntityFallingStar.java:73)
	at vazkii.botania.common.entity.EntityFallingStar.func_70071_h_(EntityFallingStar.java:58)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Terra Blade
```
java.lang.NullPointerException: Ticking entity
	at joshie.progression.criteria.triggers.TriggerKill.canIncrease(TriggerKill.java:47)
	at joshie.progression.criteria.triggers.TriggerBaseCounter.onFired(TriggerBaseCounter.java:29)
	at joshie.progression.player.CriteriaMappings.fireAllTriggers(CriteriaMappings.java:227)
	at joshie.progression.handlers.APIHandler.fireTrigger(APIHandler.java:53)
	at joshie.progression.handlers.APIHandler.fireTrigger(APIHandler.java:60)
	at joshie.progression.criteria.triggers.TriggerKill.onEvent(TriggerKill.java:29)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_689_TriggerKill_onEvent_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraSword.updateBurst(ItemTerraSword.java:122)
	at vazkii.botania.common.entity.EntityManaBurst.func_70071_h_(EntityManaBurst.java:366)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

```

**Comment by Vazkii** [comment]
Doesn't look like a botania issue, report this to the other mod.
