### ISSUE TITLE
crash with black hole talisman

### ISSUE THREAD

**Issue by torterra2234** [Vazkii/Botania#1503]
on setting a black hole talisman to absorb redstone ore i get a crash to desktop, does not seem to happen with any other materials or seem to be due to having a large number of them in my inventory, each crash gives the same null pointer, only seems to occur when taliman is on:

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at vazkii.botania.common.item.ItemBlackHoleTalisman.func_77624_a(ItemBlackHoleTalisman.java:258)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at vazkii.botania.client.core.handler.TooltipAdditionDisplayHandler.render(TooltipAdditionDisplayHandler.java:62)
	at vazkii.botania.client.core.handler.ClientTickHandler.renderTick(ClientTickHandler.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_844_ClientTickHandler_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
