### ISSUE TITLE
EntityThornChakram crash on startup

### ISSUE THREAD

**Issue by cjthomp** [Vazkii/Botania#1766]
Crafted a Thorn Chakram, tossed it a few times, one of those tosses caused the game to crash, and now it crashes every time I start, same error

1.8.9, updated Forge, updated Botania, updated Thaumcraft

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/19/16 2:17 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.func_175701_a(World.java:199)
	at net.minecraft.world.World.func_180495_p(World.java:814)
	at vazkii.botania.common.entity.EntityThornChakram.func_70184_a(EntityThornChakram.java:114)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.botania.common.entity.EntityThornChakram.func_70071_h_(EntityThornChakram.java:60)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.World.func_175701_a(World.java:199)
	at net.minecraft.world.World.func_180495_p(World.java:814)
	at vazkii.botania.common.entity.EntityThornChakram.func_70184_a(EntityThornChakram.java:114)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.botania.common.entity.EntityThornChakram.func_70071_h_(EntityThornChakram.java:60)
	at net.minecraft.world.World.func_72866_a(World.java:1860)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1829)

-- Entity being ticked --
Details:
	Entity Type: Botania.botania:thornChakram (vazkii.botania.common.entity.EntityThornChakram)
	Entity ID: 70
	Entity Name: Thorn Chakram
	Entity's Exact location: -122.14, 59.55, 224.44
	Entity's Block location: -123.00,59.00,224.00 - World: (-123,59,224), Chunk: (at 5,3,0 in -8,14; contains blocks -128,0,224 to -113,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -1.34, -0.30, -0.29
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1661)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: EbuPack 1.8.9
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -5831533838670645742
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -192.00,64.00,252.00 - World: (-192,64,252), Chunk: (at 0,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1670643 game time, 60315 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86572 (now: false), thunder time: 16063 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349594024 bytes (333 MB) / 812666880 bytes (775 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.0.1696 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1696.jar) 
	UCHIJAAAA	Forge{11.15.0.1696} [Minecraft Forge] (forge-1.8.9-11.15.0.1696.jar) 
	UCHIJAAAA	advInv{0.6.0} [Advanced Inventory] (advInv-0.6.0-MC1.8.9.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.2} [Thaumcraft] (Thaumcraft-1.8.9-5.1.2.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-64e3a96.jar) 
	UCHIJAAAA	fe{1.1} [Food Expansion] (FoodExpansion1.1-mc1.8.9.jar) 
	UCHIJAAAA	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
	UCHIJAAAA	IronChest{6.0.115.759} [Iron Chest] (ironchest-1.8.9-6.0.115.759.jar) 
	UCHIJAAAA	JEI{2.16.2.78} [Just Enough Items] (jei_1.8.9-2.16.2.78.jar) 
	UCHIJAAAA	JEIAddons{0.8.1.30} [Just Enough Items Addons] (JEIAddons_1.8.9-0.8.1.30.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	middletorch{2.0.3} [The Middle Torch] (middletorch-2.0.3.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar) 
	UCHIJAAAA	fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
	UCHIJAAAA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by AlterAkima** [comment]
1.8 crashes are reported there: https://github.com/williewillus/Botania/issues

**Comment by cjthomp** [comment]
Damn it, I knew that.
