### ISSUE TITLE
Forge Not detected on Server

### ISSUE THREAD

**Issue by RobertLSnead** [Vazkii/Botania#1907]
MC 1.10.2
Forge 12.18.1.2095
Botania r1.9-327

Works fine on client!
I receive the following error when loading on my server:

Missing Mods:
	Forge : [12.18.1.2053,]

net.minecraftforge.fml.common.MissingModsException: Mod Botania (Botania) requires [Forge@[12.18.1.2053,]]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:274)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yrsegal** [comment]
is the Forge version on the server older?

**Comment by RobertLSnead** [comment]
It is the one I listed Forge 12.18.1.2095!  Works fine on client and server version Forge 12.18.1.2088!

**Comment by RobertLSnead** [comment]
Reverted back to 12.18.1.2088 for now!
