### ISSUE TITLE
Crashing after updating

### ISSUE THREAD

**Issue by PsycoXGoldhawk** [Vazkii/Botania#1919]
So I updated my Botania to the most recent version at the time of writing this, r1.9-328, and my server seems to be crashing but all I can see is botania. Could be the modpack(All The Mods lite) I am using but I am not to sure.
[crash-2016-10-07_13.54.34-server.txt](https://github.com/Vazkii/Botania/files/516058/crash-2016-10-07_13.54.34-server.txt)

**Comment by MoonCutter2B** [comment]
I crash too :(

first few lines in my log say:

java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
	at vazkii.botania.client.core.handler.HUDHandler.onDrawScreenPre(HUDHandler.java:91)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_HUDHandler_onDrawScreenPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:884)

**Comment by ArukaAlter** [comment]
Don't use Baubles beta, and read closed issues.

**Comment by PsycoXGoldhawk** [comment]
and my issue?

**Comment by ArukaAlter** [comment]
Sorry, the other person messed me up.
What version were you using before updating.

**Comment by PsycoXGoldhawk** [comment]
No Problem.
Botania r1.9-326
