### ISSUE TITLE
1.10 any version crash

### ISSUE THREAD

**Issue by RPGMADMAN** [Vazkii/Botania#1981]
everytime i launch minecraft with botania it crashes me when i remove it it works just fine and i dont know whats up here what it says:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/26/16 11:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:797)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at cofh.api.energy.ItemEnergyContainer.receiveEnergy(ItemEnergyContainer.java:66)
	at refinedstorage.item.ItemWirelessGrid.func_150895_a(ItemWirelessGrid.java:96)
	at vazkii.botania.client.core.handler.CorporeaAutoCompleteHandler.updateItemList(CorporeaAutoCompleteHandler.java:61)
	at vazkii.botania.client.core.proxy.ClientProxy.postInit(ClientProxy.java:236)
	at vazkii.botania.common.Botania.postInit(Botania.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 371686888 bytes (354 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	UCHIJ	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	UCHIJ	Baubles{1.3.BETA11} [Baubles] (Baubles-1.10.2-1.3.BETA11.jar) 
	UCHIE	Botania{r1.9-335} [Botania] (Botania r1.9-335.jar) 
	UCHIJ	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJ	chiselsandbits{12.6} [Chisels & Bits] (chiselsandbits-12.6.jar) 
	UCHIJ	IC2{2.6.1-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.1-ex110.jar) 
	UCHIJ	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
	UCHIJ	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJ	ElecCore{1.6.328} [ElecCore] (ElecCore-1.10.2-1.6.328.jar) 
	UCHIJ	deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
	UCHIJ	DungeonTactics{DT0.9.5} [DungeonTactics] (DungeonTactics-1.10.2-0.9.5.jar) 
	UCHIJ	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCHIJ	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UCHIJ	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJ	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJ	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJ	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJ	reap{1.3.0} [Reap Mod] (ReapMod 1.3.0.jar) 
	UCHIJ	refinedstorage{1.1.3} [Refined Storage] (refinedstorage-1.1.3.jar) 
	UCHIJ	xreliquary{1.10.2-1.3.3.581} [Reliquary] (Reliquary-1.10.2-1.3.3.581.jar) 
	UCHIJ	rftools{5.56} [RFTools] (rftools-1.10-5.56.jar) 
	UCHIJ	rftoolsdim{4.43} [RFTools Dimensions] (rftoolsdim-1.10-4.43.jar) 
	UCHIJ	roots{0.112} [Roots] (roots-1.10.2-0.112.0.jar) 
	UCHIJ	flammpfeil.slashblade{mc1.9.4-r15} [SlashBlade] (SlashBlade-mc1.9.4-r15b.jar) 
	UCHIJ	tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct] (TConstruct-1.10.2-2.5.3.jar) 
	UCHIJ	theoneprobe{1.2.0} [The One Probe] (theoneprobe-1.10-1.2.0.jar) 
	UCHIJ	waystones{2.0.4} [Waystones] (Waystones_1.10.2-2.0.4.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11774 Compatibility Profile Context' Renderer: 'AMD Radeon HD 7550M/7650M Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by williewillus** [comment]
The mod that is actually ausing the issue is refined storage.

**Comment by RPGMADMAN** [comment]
oh ok thx

2016-10-27 2:07 GMT+03:00 Vincent Lee <notifications@github.com>:
