### ISSUE TITLE
Client crash when player is walking through someones botania setup on a server.

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#1999]
http://pastebin.com/aBZKi5f3

Thread: Client thread
Stacktrace:
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.remove(ArrayList.java:865)
    at net.minecraft.world.World.func_175690_a(World.java:2451)
    at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
    at net.minecraft.world.ChunkCache.func_190300_a(ChunkCache.java:74)
    at net.minecraft.world.ChunkCache.func_175625_s(ChunkCache.java:64)
    at vazkii.botania.common.block.BlockPlatform.getExtendedState(BlockPlatform.java:99)

**Comment by Vazkii** [comment]
Ok, I'm totally stumped on this one. I'll ping @williewillus

**Comment by Tamaized** [comment]
`world.getTileEntity(pos)` crashes at line 99 but not 98 o-0 wot? Figure if that really is the case just grab the TE instance once and not twice? idk

**Comment by williewillus** [comment]
note to self, in getextendedstate try using the overload of getTE that only reads, not writes.

I'll look at this soon(tm)
