### ISSUE TITLE
1.10.2 r1.9-335 Crash

### ISSUE THREAD

**Issue by subarct1c** [Vazkii/Botania#2000]
http://pastebin.com/Tkdep43h
http://pastebin.com/eYzeqPK0

java.lang.IndexOutOfBoundsException: Index: 5, Size: 6
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.world.World.func_189508_F(World.java:2419)
	at net.minecraft.world.World.func_175625_s(World.java:2397)
	at vazkii.botania.api.subtile.SubTileGenerating.isValidBinding(SubTileGenerating.java:304)
	at vazkii.botania.api.subtile.SubTileGenerating.emptyManaIntoCollector(SubTileGenerating.java:160)
	at vazkii.botania.api.subtile.SubTileGenerating.onUpdate(SubTileGenerating.java:84)
	at vazkii.botania.common.block.subtile.generating.SubTileEndoflame.onUpdate(SubTileEndoflame.java:41)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_73660_a(TileSpecialFlower.java:100)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.World.func_189508_F(World.java:2421)
	at net.minecraft.world.World.func_175625_s(World.java:2407)
	at vazkii.botania.common.block.tile.mana.TileSpreader.func_73660_a(TileSpreader.java:198)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Crash has happened 2 times with the first error, and 1 time with the second. All while either being around Botania items but not interacting with them.

**Comment by Vazkii** [comment]
Try without optifine. Closing for now.
