### ISSUE TITLE
ItemGoddessCharm - crash

### ISSUE THREAD

**Issue by Ronnon78** [Vazkii/Botania#2012]
`
// I blame Dinnerbone.

Time: 03.11.16 22:20
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at vazkii.botania.common.item.equipment.bauble.ItemGoddessCharm.onExplosion(ItemGoddessCharm.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_173_ItemGoddessCharm_onExplosion_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:452)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:133)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1174)
	at net.minecraft.world.World.func_72876_a(World.java:2303)
	at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:243)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:154)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at vazkii.botania.common.item.equipment.bauble.ItemGoddessCharm.onExplosion(ItemGoddessCharm.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_173_ItemGoddessCharm_onExplosion_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:452)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:133)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1174)
	at net.minecraft.world.World.func_72876_a(World.java:2303)
	at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:243)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:154)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: Creeper (net.minecraft.entity.monster.EntityCreeper)
	Entity ID: 389
	Entity Name: Creeper
	Entity's Exact location: -145,55, 77,00, -259,35
	Entity's Block location: World: (-146,77,-260), Chunk: (at 14,4,12 in -10,-17; contains blocks -160,0,-272 to -145,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
`

mod version: Botania r1.9-336.jar

**Comment by Febilian** [comment]
This would have been fixed in version 337, you're using the version before that(336). Update and it should be fine.

**Comment by Vazkii** [comment]
Fixed in the latest.

**Comment by Ronnon78** [comment]
Ok. Thanks
