### ISSUE TITLE
Player flying past floating flowers repeatedly crashes on login.

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#2071]
http://pastebin.com/ms7VxSNU

Description: Tesselating block model
 
java.lang.NullPointerException: Tesselating block model
    at vazkii.botania.client.model.FloatingFlowerModel.getModel(FloatingFlowerModel.java:124)
    at vazkii.botania.client.model.FloatingFlowerModel.func_188616_a(FloatingFlowerModel.java:105)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)

**Comment by williewillus** [comment]
`at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)`

what mod is this? they are breaking the normal forge renderer

**Comment by ProsperCraft** [comment]
Not sure, its the stock FTB Infinity Lite 1.3.3

**Comment by M91** [comment]
i only seen this when i have Optifine installed. if you have it installed on the client, remove it and try again.
