### ISSUE TITLE
Unknown server crash with Botania related lines

### ISSUE THREAD

**Issue by Zaflis** [Vazkii/Botania#2076]
We are using DW20's latest modpack version 1.1.4. 

    [17:59:38] [Server thread/ERROR]: Encountered an unexpected exception
    net.minecraft.util.ReportedException: Ticking block entity
            at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
            at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
            at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
            at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
            at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
    Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.AltarVariant, values=[DEFAULT, FOREST, PLAINS, MOUNTAIN, FUNGAL, SWAMP, DESERT, TAIGA, MESA, MOSSY]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
            at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
            at vazkii.botania.common.block.tile.TileAltar.collideEntityItem(TileAltar.java:75) ~[TileAltar.class:?]
            at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:252) ~[TileAltar.class:?]
            at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
            at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
            at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
            ... 4 more

**Comment by Zaflis** [comment]
And maybe this helps too

    -- Block entity being ticked --
    Details:
      Name: botania:altar // vazkii.botania.common.block.tile.TileAltar
      Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
      Block data value: 0 / 0x0 / 0b0000
      Block location: World: (208,69,-6), Chunk: (at 0,4,10 in 13,-1; contains blocks 208,0,-16 to 223,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
      Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
      Actual block data value: 0 / 0x0 / 0b0000

**Comment by ArukaAlter** [comment]
https://github.com/Vazkii/Botania/blob/master/contributing.md

**Comment by Zaflis** [comment]
What are you trying to say? I went through all the open and closed issues, but none was anything like this.

**Comment by yrsegal** [comment]
Aruka, this is absolutely enough info for the bug to be fixed

**Comment by yrsegal** [comment]
oftentimes getting a blockstate at a pos won't work for tiles, and this has to be checked for
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/tile/TileAltar.java#L75

**Comment by Zaflis** [comment]
New server crashlog when playing Sky Factory 3 in multiplayer http://pastebin.com/2SQ5wfVg
Now i keep getting:

    "Failed to login: The Server encountered an unexpected condition which prevented it from fulfilling the request"

Friend had that too but after 1 or 2 tries he got on, i still can't after 10 tries. Maybe rolling a backup from 2 hours ago.

In his words what happened: "I was about to craft pure daisy...put seeds on top of the petal thingy and dropped the petal but they didnt go in to the petal thing and that was cause of crash".

And at the same time i was half way through on laying obsidian to build a nether portal. (unrelated)

**Comment by MissPotato** [comment]
A temporary fix would be /setblock -17 57 26 air it looks like a botania block, specifically "TileAltar." I don't quite understand the bug itself to fully define it for you. But it just isn't ticking well.

**Comment by williewillus** [comment]
An apothecary TE somehow ended up in a block of air. Either enable forge 's "remove erroring TE's" config or use /setblock

**Comment by williewillus** [comment]
#2205
