### ISSUE TITLE
mana pool tries to get is blockstate from y0

### ISSUE THREAD

**Issue by EnderiumSmith** [Vazkii/Botania#2086]
the crash started around when i got fabulous mana pools. the first time i start the game after restarting the computer the game crashes. after that it works fine.

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.PoolVariant, values=[DEFAULT, CREATIVE, DILUTED, FABULOUS]} as it does not exist in BlockStateContainer{block=minecraft:bedrock, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at vazkii.botania.common.block.tile.mana.TilePool.func_73660_a(TilePool.java:222)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at vazkii.botania.common.block.tile.mana.TilePool.func_73660_a(TilePool.java:222)

-- Block entity being ticked --
Details:
	Name: botania:pool // vazkii.botania.common.block.tile.mana.TilePool
	Block type: ID #7 (tile.bedrock // net.minecraft.block.BlockEmptyDrops)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-143,0,-190), Chunk: (at 1,0,2 in -9,-12; contains blocks -144,0,-192 to -129,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #7 (tile.bedrock // net.minecraft.block.BlockEmptyDrops)
	Actual block data value: 0 / 0x0 / 0b0000

**Comment by williewillus** [comment]
#2205
