### ISSUE TITLE
[1.7.10] Crash with AcademyCraft

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2092]
I know that 1.7.10 isn't supported, I just want to know if there is a way to fix this either on my end, or if AC has to do something (since they're still on 1.7.10).

https://gist.githubusercontent.com/Zsashas/93d4844a44b4b81461933bda57eb3117/raw/c9c7a961c1b7964202d86dca0a7baaa56f93e002/AC%2520Crash

Crash happens when trying to load a singleplayer world.

**Comment by williewillus** [comment]
i'm not sure if this is botania's fault, it's not anywhere in the stacktrace

**Comment by Zsashas** [comment]
Um, really? 

Stacktrace:
	at vazkii.botania.common.item.ItemManaGun.getBurst(ItemManaGun.java:200)
	at vazkii.botania.common.item.ItemManaGun.func_82790_a(ItemManaGun.java:163)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

**Comment by williewillus** [comment]
I stand corrected.
1.7 is still unsupported though :P 
does it happen without "AC"?

**Comment by Zsashas** [comment]
No idea how to test that since I don't know what caused it to begin with.

**Comment by Zsashas** [comment]
None of my worlds are crashing now.
