### ISSUE TITLE
Crash when changing dimension

### ISSUE THREAD

**Issue by Eufranio** [Vazkii/Botania#2098]
I have a red string comparator, and whenever I change dimension, I crash with this:
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at vazkii.botania.common.block.tile.string.TileRedString.getOrientation(TileRedString.java:80)
	at vazkii.botania.client.core.handler.RedStringRenderer.renderTile(RedStringRenderer.java:78)
	at vazkii.botania.client.core.handler.RedStringRenderer.renderAll(RedStringRenderer.java:48)
	at vazkii.botania.client.core.handler.LightningHandler.onRenderWorldLast(LightningHandler.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_444_LightningHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:332)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1871)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```
Full crash-report: https://hastebin.com/ixerewepej.scala

**Comment by williewillus** [comment]
#2205
