### ISSUE TITLE
Server crash when attempting to use Cacophonium on a note block (w/ Charset mod)

### ISSUE THREAD

**Issue by kingofrunes** [Vazkii/Botania#2106]
When attempting to use cacophonium on a note block the following crash was generated:

java.lang.NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503_a()Lnet/minecraft/util/ResourceLocation;
	at pl.asie.charset.audio.note.NoteBlockManager.onNoteEvent(NoteBlockManager.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_427_NoteBlockManager_onNoteEvent_Play.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.block.BlockNote.func_189539_a(BlockNote.java:111)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1231)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1218)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

Looks like it has a problem when charset mod is installed on the server. Is this something you can fix Vazkii or is it something I need to send over to the mod author of charset?

**Comment by TheWhiteWolves** [comment]
looks like its more something on charsets side, that's what is throwing the error.

**Comment by kingofrunes** [comment]
I"m going to go ahead and close it and open up a ticket on charset end then.
