### ISSUE TITLE
Sponge 2117 after stop server

### ISSUE THREAD

**Issue by mkrtes** [Vazkii/Botania#2159]
```
[23:46:38] [Server thread/INFO]: Stopping server
[23:46:38] [Server thread/INFO]: Saving players
[23:46:38] [Server thread/INFO]: Saving worlds
[23:46:38] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[23:46:38] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[23:46:38] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[23:46:38] [Server thread/INFO]: Saving chunks for level 'DIM-11325'/Deep Dark
[23:46:38] [Server thread/INFO]: Saving chunks for level 'DIM-9999'/ExtraUtils2_Quarry_Dim
[23:46:38] [Server thread/INFO] [Sponge]: Unloading world [world] (DIM0)
[23:46:38] [Server thread/INFO] [Actually Additions]: Unloading WorldData for world 0!
[23:46:38] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
[23:46:38] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Unload@3f9ee362:
java.lang.NullPointerException
        at net.minecraft.world.World.handler$onGetMapStorage$zpf000(World.java:7986) ~[aid.class:?]
        at net.minecraft.world.World.func_175693_T(World.java) ~[aid.class:?]
        at vazkii.botania.common.block.BlockPistonRelay$WorldData.get(BlockPistonRelay.java:184) ~[BlockPistonRelay$WorldData.class:?]
        at vazkii.botania.common.block.BlockPistonRelay.onWorldUnload(BlockPistonRelay.java:149) ~[BlockPistonRelay.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_BlockPistonRelay_onWorldUnload_Unload.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:637) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callWorldUnloadEvent(SpongeForgeEventFactory.java:1218) [SpongeForgeEventFactory.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:478) [SpongeForgeEventFactory.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) [SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) [SpongeImpl.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:504) [WorldManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) [DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[23:46:38] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[23:46:38] [Server thread/ERROR] [FML]: 0: HIGHEST
[23:46:38] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@2f3f68dc onDimensionUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 2: NORMAL
[23:46:38] [Server thread/ERROR] [FML]: 3: ASM: it.zerono.mods.zerocore.internal.common.MultiblockEventHandler@4469ed7 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 4: ASM: Block{botania:pistonRelay} onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 5: ASM: ic2.core.IC2@3f621c85 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 6: ASM: forestry.core.EventHandlerCore@6baac3b3 handleWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 7: ASM: forestry.core.multiblock.MultiblockEventHandler@4d171ecf onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 8: ASM: elec332.core.server.SaveHandler$EventHandler@39c3bb43 worldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 9: ASM: elec332.core.grid.internal.GridEventHandler@5a7001a3 worldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 10: ASM: codechicken.enderstorage.network.TankSynchroniser@16b381be onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 11: ASM: com.rwtema.extrautils2.chunkloading.XUChunkLoaderManager@2678a61c onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 12: ASM: de.ellpeck.actuallyadditions.mod.event.CommonEvents@7665cadd onUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 13: ASM: appeng.hooks.TickHandler@2cd661af unloadWorld(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 14: ASM: ic2.core.ChunkLoaderLogic@3301832b unloadWorld(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 15: ASM: li.cil.oc.common.EventHandler$@7fb3c1e7 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 16: ASM: li.cil.oc.common.item.Tablet$@583802d7 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 17: ASM: li.cil.oc.server.network.Waypoints$@fa6ccf6 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 18: ASM: li.cil.oc.server.network.WirelessNetwork$@78413277 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 19: ASM: li.cil.oc.client.ComponentTracker$@47abf8a5 onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 20: ASM: li.cil.oc.server.ComponentTracker$@2d03d12b onWorldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 21: ASM: com.brandon3055.draconicevolution.world.WorldTickHandler@6f5f51d9 worldUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 22: ASM: blusunrize.immersiveengineering.common.EventHandler@342cf814 onUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR] [FML]: 23: LOWEST
[23:46:38] [Server thread/ERROR] [FML]: 24: ASM: com.rwtema.extrautils2.chunkloading.XUChunkLoaderManager@2678a61c worldLoad(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[23:46:38] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException
        at net.minecraft.world.World.handler$onGetMapStorage$zpf000(World.java:7986) ~[aid.class:?]
        at net.minecraft.world.World.func_175693_T(World.java) ~[aid.class:?]
        at vazkii.botania.common.block.BlockPistonRelay$WorldData.get(BlockPistonRelay.java:184) ~[BlockPistonRelay$WorldData.class:?]
        at vazkii.botania.common.block.BlockPistonRelay.onWorldUnload(BlockPistonRelay.java:149) ~[BlockPistonRelay.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_BlockPistonRelay_onWorldUnload_Unload.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:637) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callWorldUnloadEvent(SpongeForgeEventFactory.java:1218) ~[SpongeForgeEventFactory.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:478) ~[SpongeForgeEventFactory.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:281) ~[SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2221-5.1.0-BETA-2117]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:504) ~[WorldManager.class:1.10.2-2221-5.1.0-BETA-2117]
        at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:654) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[23:46:39] [Server thread/INFO] [FML]: Applying holder lookups
[23:46:39] [Server thread/INFO] [FML]: Holder lookups applied
[23:46:39] [Server thread/INFO] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Close initiated...
[23:46:39] [Server thread/INFO] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Closed.
[23:46:39] [Server thread/INFO] [nucleus]: Nucleus is performing server shutdown tasks.
[23:46:39] [Server thread/INFO] [mcjty.lib.varia.Logging]: Deep Resonance: server is stopping. Shutting down gracefully
[23:46:39] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[23:46:39] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[23:46:39] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
[23:46:39] [Server Shutdown Thread/INFO]: Stopping server
[23:46:39] [Server Shutdown Thread/INFO]: Saving players
[23:46:39] [Server Shutdown Thread/INFO]: Saving worlds
[23:46:39] [Server Shutdown Thread/INFO]: Saving chunks for level 'DIM1'/The End

```

Is this botania error or Sponge?

**Comment by chazwarp923** [comment]
I was getting this crash as well and i did some testing.
I tested SpongeForge versions 2102, 2103, 2104 and 2136.
I was getting crashes from Extra Utilities 2 until 2104, and i reproduced the above crash on 2136.
So I'd venture to say that sponge changed something sometime in between 2104 and 2117 that is now causing the crash.

**Comment by williewillus** [comment]
do you have a full log?

**Comment by chazwarp923** [comment]
The log as asked for.
Forge version: 2239
Sponge Version: 2136
[fml-server-latest.zip](https://github.com/Vazkii/Botania/files/840545/fml-server-latest.zip)
However, i did some more testing and it appears the error no longer happens on sponge 2229 and the same forge.
