### ISSUE TITLE
[1.11.2] Crash Rendering screen and JEI bug

### ISSUE THREAD

**Issue by allanf181** [Vazkii/Botania#2214]
![screenshot 1952](https://cloud.githubusercontent.com/assets/14101716/24276224/d1aa8074-1013-11e7-8596-d00d63f16e2b.png)
I used this image because the error is happening with another mod as well (which uses the botania api).
```java
[21:52:01] [Client thread/ERROR] [jei/]: Failed to get tooltip: 1xitem.twigWand@0 botania:twigwand nbt:{color1:1,color2:1}
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777) ~[afj.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:42) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:20) [ItemStackRenderer.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.getIngredientTooltipSafe(GuiIngredientFast.java:309) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.getTooltip(GuiIngredientFast.java:285) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.drawTooltip(GuiIngredientFast.java:273) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.drawTooltip(GuiIngredientFast.java:266) [GuiIngredientFast.class:?]
	at mezz.jei.gui.IngredientGrid.drawTooltips(IngredientGrid.java:108) [IngredientGrid.class:?]
	at mezz.jei.gui.ItemListOverlayInternal.drawTooltips(ItemListOverlayInternal.java:194) [ItemListOverlayInternal.class:?]
	at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:110) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_511_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:383) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at Reflector.callVoid(Reflector.java:530) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1425) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
```
```java
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TweaksLoadingPlugin (CCTweaks-1.11.2-1.3.3.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  UnborkedPlugin (unborked-1.11.2-1.80pr0-1.1.4.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  LoadingPlugin (Quark-r1.2-87.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 3/23/17 9:52 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:170)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_73863_a(GuiBase.java:104)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1425)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:170)
	at com.raoulvdberge.refinedstorage.gui.GuiBase.func_73863_a(GuiBase.java:104)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:530)

-- Screen render details --
Details:
	Screen name: com.raoulvdberge.refinedstorage.gui.grid.GuiGrid
	Mouse location: Scaled: (248, 106). Absolute: (496, 267)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['armelin1'/1966, l='MpServer', x=96.27, y=80.00, z=79.76], EntityOtherPlayerMP['D4rkness_King'/1322, l='MpServer', x=50.83, y=83.00, z=79.87]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,68,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15465834 game time, 9878507 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 80 total; [EntityWorm['Worm'/0, l='MpServer', x=50.50, y=69.50, z=65.50], EntityWorm['Worm'/1, l='MpServer', x=51.50, y=69.50, z=70.50], EntityWorm['Worm'/2, l='MpServer', x=87.50, y=79.50, z=74.50], EntityItemFrame['entity.ItemFrame.name'/3, l='MpServer', x=61.03, y=84.50, z=58.50], EntityItem['item.item.rottenFlesh'/1805, l='MpServer', x=43.82, y=67.00, z=81.75], EntityEnderman['Enderman'/1429, l='MpServer', x=130.10, y=44.00, z=54.80], EntitySkeleton['Skeleton'/1941, l='MpServer', x=42.70, y=75.00, z=85.23], EntitySkeleton['Skeleton'/2070, l='MpServer', x=109.50, y=40.00, z=70.50], EntitySkeleton['Skeleton'/2072, l='MpServer', x=127.50, y=79.00, z=119.50], EntitySkeleton['Skeleton'/2075, l='MpServer', x=33.50, y=75.00, z=84.50], EntityBat['Bat'/1308, l='MpServer', x=76.36, y=22.10, z=35.29], EntityZombie['Zombie'/2076, l='MpServer', x=41.85, y=67.00, z=90.66], EntityZombie['Zombie'/1950, l='MpServer', x=34.50, y=75.00, z=84.27], EntityZombie['Zombie'/2078, l='MpServer', x=42.50, y=75.00, z=88.50], EntityZombie['Zombie'/2079, l='MpServer', x=41.50, y=71.00, z=90.50], EntitySpider['Spider'/2080, l='MpServer', x=41.28, y=67.00, z=86.68], EntityCreeper['Creeper'/2082, l='MpServer', x=32.30, y=75.00, z=83.52], EntityCreeper['Creeper'/2086, l='MpServer', x=41.74, y=75.00, z=90.66], EntityZombie['Zombie'/1959, l='MpServer', x=32.45, y=67.00, z=90.70], EntityItem['item.item.redstone'/2088, l='MpServer', x=41.53, y=67.00, z=82.14], EntityItem['item.item.stick'/2089, l='MpServer', x=41.30, y=67.00, z=81.36], EntityOtherPlayerMP['D4rkness_King'/1322, l='MpServer', x=50.83, y=83.00, z=79.87], EntitySpider['Spider'/2091, l='MpServer', x=32.80, y=71.00, z=88.43], EntitySpider['Spider'/1836, l='MpServer', x=36.03, y=78.10, z=90.30], EntityItem['item.item.string'/2094, l='MpServer', x=43.42, y=67.00, z=81.13], EntityWorm['Worm'/175, l='MpServer', x=62.50, y=74.50, z=17.50], EntityZombie['Zombie'/2095, l='MpServer', x=39.50, y=67.00, z=86.50], EntityWorm['Worm'/176, l='MpServer', x=62.50, y=74.50, z=23.50], EntityZombie['Zombie'/2096, l='MpServer', x=40.50, y=67.00, z=84.50], EntityWorm['Worm'/177, l='MpServer', x=62.50, y=74.50, z=20.50], EntityCreeper['Creeper'/1970, l='MpServer', x=30.50, y=36.00, z=124.50], EntityCreeper['Creeper'/2098, l='MpServer', x=40.25, y=71.00, z=86.67], EntityWorm['Worm'/183, l='MpServer', x=68.50, y=74.50, z=17.50], EntitySheep['Sheep'/1335, l='MpServer', x=116.50, y=79.00, z=145.50], EntityCreeper['Creeper'/1975, l='MpServer', x=30.50, y=36.00, z=124.50], EntitySheep['Sheep'/1336, l='MpServer', x=115.50, y=79.00, z=145.50], EntityCreeper['Creeper'/1337, l='MpServer', x=128.50, y=41.00, z=119.50], EntityItem['item.item.seeds'/1338, l='MpServer', x=140.49, y=98.00, z=65.74], EntitySkeleton['Skeleton'/1339, l='MpServer', x=144.50, y=62.00, z=105.50], EntityZombie['Zombie'/1212, l='MpServer', x=88.50, y=42.00, z=118.50], EntityWorm['Worm'/190, l='MpServer', x=86.50, y=79.50, z=84.50], EntityCreeper['Creeper'/1982, l='MpServer', x=30.50, y=36.00, z=124.50], EntityWorm['Worm'/191, l='MpServer', x=83.50, y=79.50, z=85.50], EntityLlama['Llama'/192, l='MpServer', x=83.46, y=78.00, z=91.96], EntityLlama['Llama'/193, l='MpServer', x=84.46, y=78.00, z=90.91], EntityCreeper['Creeper'/1986, l='MpServer', x=79.50, y=56.00, z=105.50], EntityItem['item.item.sulphur'/1859, l='MpServer', x=42.48, y=67.00, z=82.19], EntitySkeleton['Skeleton'/1987, l='MpServer', x=79.50, y=56.00, z=105.50], EntityPlayerSP['armelin1'/1966, l='MpServer', x=96.27, y=80.00, z=79.76], EntitySpider['Spider'/1736, l='MpServer', x=33.58, y=67.00, z=85.17], EntityCreeper['Creeper'/1992, l='MpServer', x=100.50, y=14.00, z=115.50], EntityZombie['Zombie'/1869, l='MpServer', x=32.30, y=67.00, z=84.99], EntitySkeleton['Skeleton'/1229, l='MpServer', x=42.50, y=30.00, z=115.50], EntitySkeleton['Skeleton'/2003, l='MpServer', x=136.50, y=68.00, z=30.50], EntityItem['item.item.arrow'/1751, l='MpServer', x=43.00, y=67.00, z=81.88], EntityZombie['Zombie'/2009, l='MpServer', x=32.50, y=79.00, z=107.50], EntityItem['item.item.string'/1886, l='MpServer', x=36.13, y=67.00, z=81.78], EntityZombieVillager['Zombie Villager'/1887, l='MpServer', x=41.07, y=75.00, z=83.58], EntityItem['item.item.arrow'/1888, l='MpServer', x=37.56, y=67.00, z=82.74], EntityZombie['Zombie'/2023, l='MpServer', x=115.50, y=18.00, z=88.50], EntitySpider['Spider'/1900, l='MpServer', x=32.70, y=78.10, z=86.17], EntityZombie['Zombie'/2028, l='MpServer', x=51.50, y=21.00, z=123.50], EntitySkeleton['Skeleton'/2030, l='MpServer', x=70.50, y=21.00, z=26.50], EntityCow['Cow'/111, l='MpServer', x=19.42, y=75.00, z=62.77], EntityItem['item.item.sugar'/1775, l='MpServer', x=35.20, y=67.00, z=81.52], EntityZombie['Zombie'/2031, l='MpServer', x=150.50, y=67.00, z=26.50], EntitySpider['Spider'/1776, l='MpServer', x=38.30, y=73.10, z=79.85], EntityItem['item.item.chickenRaw'/1905, l='MpServer', x=41.12, y=67.00, z=82.16], EntitySkeleton['Skeleton'/2033, l='MpServer', x=33.04, y=67.00, z=87.94], EntityOtherPlayerMP['D4rkness_King'/1322, l='MpServer', x=50.83, y=83.00, z=79.87], EntityChicken['Chicken'/116, l='MpServer', x=16.45, y=77.00, z=20.16], EntityCreeper['Creeper'/2036, l='MpServer', x=32.64, y=67.00, z=82.98], EntityChicken['Chicken'/117, l='MpServer', x=23.44, y=79.00, z=22.50], EntityBat['Bat'/1397, l='MpServer', x=41.25, y=13.02, z=130.25], EntityWorm['Worm'/121, l='MpServer', x=45.50, y=69.50, z=64.50], EntityWorm['Worm'/122, l='MpServer', x=45.50, y=69.50, z=70.50], EntitySkeleton['Skeleton'/1915, l='MpServer', x=32.30, y=67.00, z=84.13], EntityItem['item.item.bone'/1789, l='MpServer', x=33.25, y=67.00, z=82.55], EntityBat['Bat'/1661, l='MpServer', x=75.75, y=20.10, z=119.25], EntityItem['item.item.bone'/2047, l='MpServer', x=33.63, y=67.00, z=81.95]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 527554160 bytes (503 MB) / 2136473600 bytes (2037 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2230 Optifine OptiFine_1.11.2_HD_U_B7 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2230-universal.jar) 
	UCHIJA	forge{13.20.0.2230} [Minecraft Forge] (forge-1.11.2-13.20.0.2230-universal.jar) 
	UCHIJA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	unborked_core{1.1.4} [Unborked Core] (minecraft.jar) 
	UCHIJA	<CCTweaks ASM>{1.3.3} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJA	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJA	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHIJA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHIJA	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJA	psi{r1.1-46} [Psi] (Psi-r1.1-46.jar) 
	UCHIJA	quark{r1.2-87} [Quark] (Quark-r1.2-87.jar) 
	UCHIJA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJA	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHIJA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJA	botania{r1.9-342} [Botania] (Botania r1.9-342.jar) 
	UCHIJA	computercraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0-patched-DO-NOT-DISTRIBUTE.jar) 
	UCHIJA	cctweaks{1.3.3} [CCTweaks] (CCTweaks-1.11.2-1.3.3.jar) 
	UCHIJA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJA	neat{1.4-13} [Neat] (client-Neat 1.4-13.jar) 
	UCHIJA	cookingforblockheads{5.3.13} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.13.jar) 
	UCHIJA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHIJA	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHIJA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJA	shetiphiancore{3.4.3} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.3.jar) 
	UCHIJA	endertanks{1.5.3} [EnderTanks] (endertanks-1.11.0-1.5.3.jar) 
	UCHIJA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.0.jar) 
	UCHIJA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta2-anarchy.jar) 
	UCHIJA	waila{1.8.7} [Waila] (Hwyla-1.8.7-B21_1.11.jar) 
	UCHIJA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJA	itemscroller{0.10.3} [Item Scroller] (itemscroller-1.11.2-0.10.3.jar) 
	UCHIJA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJA	multistorage{1.3.5} [Multi-Storage] (multistorage-1.11.0-1.3.5.jar) 
	UCHIJA	fodc{1.10.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.10.0.jar) 
	UCHIJA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJA	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHIJA	rftools{5.90} [RFTools] (rftools-1.1x-5.90.jar) 
	UCHIJA	scenter{1.11.2-3.10.1} [Scenter] (scenter-1.11.2-3.10.1.jar) 
	UCHIJA	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar) 
	UCHIJA	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCHIJA	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCHIJA	tp{2.0.2} [Tiny Progressions] (tinyprogressions-1.11.2-2.0.2 (1).jar) 
	UCHIJA	topaddons{1.11.2-0.9.2} [TOP Addons] (topaddons-1.11.2-0.9.2.jar) 
	UCHIJA	unborked{1.1.4} [Unborked] (unborked-1.11.2-1.80pr0-1.1.4.jar) 
	UCHIJA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJA	xnet{1.1.2} [XNet] (xnet-1.1.2.jar) 
	Loaded coremods (and transformers): 
TweaksLoadingPlugin (CCTweaks-1.11.2-1.3.3.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  shetiphian.core.asm.ClassTransformer
UnborkedPlugin (unborked-1.11.2-1.80pr0-1.1.4.jar)
  org.squiddev.unborked.core.UnborkedTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.2-87.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.1.11156 Compatibility Profile Context' Renderer: 'AMD Radeon(TM) HD 6620G'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) HD 6620G GL version 4.1.11156 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-3520M APU with Radeon(tm) HD Graphics
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1.11156 Compatibility Profile Context
	OpenGlRenderer: AMD Radeon(TM) HD 6620G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

**Comment by allanf181** [comment]
Fixed by adding the mod to the server
