### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by redlap2** [Vazkii/Botania#2247]
Minecraft 1.11.2

forge 1.3.20.0.2282

MODS:
BiomesOPlenty-1.11.2-6.0.2.2171-universal.jar
jei_1.11.2-4.3.3.266.jar
OptiFine_1.11.2_HD_U_B7.jar

If I add Botania r1.9-342.jar, I get a crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/19/17 2:51 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
	at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
	at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
	at BetterGrass.update(BetterGrass.java:73)
	at TextureUtils.resourcesReloaded(TextureUtils.java:295)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 102466768 bytes (97 MB) / 315256832 bytes (300 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	U	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	biomesoplenty{6.0.2.2171} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2171-universal.jar) 
	U	botania{r1.9-342} [Botania] (Botania r1.9-342_1.11.2.jar) 
	U	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2282
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.78, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.78
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ArukaAlter** [comment]
It's likely due Optifine's grass coloring tweak, not on Botania's end.

**Comment by ktole1999** [comment]
remove optifine and test again.

**Comment by redlap2** [comment]
It's working now, optifine and all.

**Comment by Tamaized** [comment]
ProTip: You can close your own issues. It's also nice to tell what exactly solved the issues in case someone else comes across this same issue and needs a solution.
