### ISSUE TITLE
[1.11.2] [r1.9-343] Issue reading level.dat on world creation after installing Botania

### ISSUE THREAD

**Issue by Simbrine** [Vazkii/Botania#2264]
When the error happens, Forge puts out a dialog screen which says something like "this world is using a backed up level.dat and continuing might cause severe corruption". Pressing "yes" in the dialog to continue world loading causes the game to freeze indefinitely, with nothing being printed in the console.

Here's the Minecraft log at the point of the error:
```
[18:37:36] [Server thread/INFO]: Starting integrated minecraft server version 1.11.2
[18:37:36] [Server thread/INFO]: Generating keypair
[18:37:36] [Server thread/ERROR]: Exception reading /home/rune/.local/share/multimc/instances/1.11.2 Modded/minecraft/saves/test/level.dat
java.lang.ArrayIndexOutOfBoundsException: 640
	at net.minecraft.util.IntIdentityHashBiMap.func_186814_a(IntIdentityHashBiMap.java:100) ~[oh.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:578) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:490) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.loadIds(FMLControlledNamespacedRegistry.java:780) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadPersistentDataToStagingRegistry(PersistentRegistryManager.java:463) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:283) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bbu.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bbt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:76) [cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[18:37:38] [Server thread/INFO]: Stopping server
[18:37:38] [Server thread/INFO]: Saving players
[18:37:38] [Server thread/INFO]: Saving worlds
```
And here's a list of the mods I'm using:
```
Alternate Terrain Generation 1.11.2-2.0.1
AutoRegLib 1.1-4
Baubles 1.11-1.4.4
Biomes O' Plenty 1.11.2-6.1.0.2218 universal
Botania r1.9-343
Dynamic Surroundings 1.11.2-3.4.2.0
Fancy Block Particles 1.11.2-2.2
Just Enough Items 1.11.2-4.3.1.259
OpenComputers MC1.11.2-1.7.0.13
OptiFine 1.11.2 HD Ultra B8
Psi r1.1-47
Quark r1.2-91
Sound Filters 0.9 for 1.11
```
Note that even though Alternate Terrain Generation is installed, it has no effect; creating a default world has the same issue (ATG has a separate world type). Biomes O' Plenty is also a suspect, but it didn't present any issue without Botania installed, and these mods have always worked fine together in the past.

**Comment by Simbrine** [comment]
I do acknowledge that OptiFine is installed, but how would that influence level file loading?

**Comment by williewillus** [comment]
Good to know the cause, thanks!
