### ISSUE TITLE
[1.12.1][r1.10-347]Criteria Trigger Registration for Relic Advancement<FATAL>

### ISSUE THREAD

**Issue by GiantNuker** [Vazkii/Botania#2378]
I am working on coding an addon.
I cannot run it because of this.
In Botania's main file, `CriteriaTriggers.register(RelicBindTrigger.INSTANCE);` Crashes the game because register is not public. Here is my log.

```
2017-09-13 16:14:38,683 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:14:38] [main/INFO]: Extra: []
[16:14:38] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/T902/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --accessToken{REDACTED}, --version, 1.12.1, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[16:14:39] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:14:39] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:14:39] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:14:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:14:39] [main/INFO]: Forge Mod Loader version 14.22.0.2469 for Minecraft 1.12.1 loading
[16:14:39] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25
[16:14:39] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[16:14:39] [main/INFO]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[16:14:39] [main/INFO]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[16:14:39] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:14:39] [main/INFO]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[16:14:39] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[16:14:39] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:14:39] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:14:39] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:14:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:14:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:14:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2017-09-13 16:14:39,790 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-09-13 16:14:40,542 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:14:43] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[16:14:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:14:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:14:44] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:14:44] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:14:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:14:44] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:14:46] [main/INFO]: Setting user: Player90
[16:14:52] [main/WARN]: Skipping bad option: lastServer:
[16:14:52] [main/INFO]: LWJGL Version: 2.9.4
[16:14:53] [main/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 748083736 bytes (713 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '3.3.0 - Build 8.15.10.2696' Renderer: 'Intel(R) HD Graphics 4000'
[16:14:53] [main/INFO]: MinecraftForge v14.22.0.2469 Initialized
[16:14:53] [main/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[16:14:53] [main/INFO]: Replaced 1036 ore ingredients
[16:14:54] [main/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[16:14:54] [main/INFO]: Searching C:\Users\T902\Programming\Java\Minecraft\1.12\run\mods for mods
[16:14:56] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 217685831 nanos
[16:14:57] [main/INFO]: Forge Mod Loader has identified 8 mods to load
[16:14:57] [main/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, botaniatweaks, backslash, botania, baubles] at CLIENT
[16:14:57] [main/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, botaniatweaks, backslash, botania, baubles] at SERVER
[16:15:02] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Botania Tweaks, FMLFileResourcePack:BackSlash API, FMLFileResourcePack:Botania, FMLFileResourcePack:Baubles
[16:15:02] [main/WARN]: ResourcePack: ignored non-lowercase namespace: Stripper.exe in C:\Users\T902\Programming\Java\Minecraft\1.12\libs\Botania r1.10-347-deobf.jar
[16:15:02] [main/INFO]: Processing ObjectHolder annotations
[16:15:02] [main/INFO]: Found 1169 ObjectHolder annotations
[16:15:02] [main/INFO]: Identifying ItemStackHolder annotations
[16:15:02] [main/INFO]: Found 0 ItemStackHolder annotations
[16:15:03] [main/INFO]: Configured a dormant chunk cache size of 0
[16:15:03] [Forge Version Check/INFO]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:15:04] [Forge Version Check/INFO]: [forge] Found status: OUTDATED Target: 14.22.1.2478
[16:15:05] [main/ERROR]: Skipping event FMLPreInitializationEvent and marking errored mod botaniatweaks since required dependency botania has errored
[16:15:05] [main/INFO]: [mods.giantnuker.backslash.Logger:logMsg:15]: [BackSlash API]: -----Starting Block Registration-----
[16:15:05] [main/INFO]: [mods.giantnuker.backslash.Logger:logMsg:15]: [BackSlash API]: -----Finished Block Registration-----
[16:15:05] [main/INFO]: Applying holder lookups
[16:15:05] [main/INFO]: Holder lookups applied
[16:15:05] [main/INFO]: [mods.giantnuker.backslash.Logger:logMsg:15]: [BackSlash API]: -----Starting Item Registration-----
[16:15:05] [main/INFO]: [mods.giantnuker.backslash.Logger:logMsg:15]: [BackSlash API]: -----Finished Item Registration-----
[16:15:05] [main/INFO]: Applying holder lookups
[16:15:05] [main/INFO]: Holder lookups applied
[16:15:05] [main/INFO]: Applying holder lookups
[16:15:05] [main/INFO]: Holder lookups applied
[16:15:05] [main/INFO]: OBJLoader: Domain botania has been added.
[16:15:06] [main/INFO]: Applying holder lookups
[16:15:06] [main/INFO]: Holder lookups applied
[16:15:06] [main/INFO]: Injecting itemstacks
[16:15:06] [main/INFO]: Itemstack injection complete
[16:15:06] [main/FATAL]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[16:15:06] [main/FATAL]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                           | Signature |
	|:----- |:------------- |:------------ |:-------------------------------- |:--------- |
	| UCH   | minecraft     | 1.12.1       | minecraft.jar                    | None      |
	| UCH   | mcp           | 9.19         | minecraft.jar                    | None      |
	| UCH   | FML           | 8.0.99.99    | forgeBin-1.12.1-14.22.0.2469.jar | None      |
	| UCH   | forge         | 14.22.0.2469 | forgeBin-1.12.1-14.22.0.2469.jar | None      |
	| UCH   | baubles       | 1.5.1        | Baubles-1.12-1.5.1.jar           | None      |
	| UCE   | botania       | r1.10-347    | Botania r1.10-347-deobf.jar      | None      |
	| UCE   | botaniatweaks | 1.12-1.0.0   | bin                              | None      |
	| UCH   | backslash     | 1.12-3.0.0   | [1.12]BackSlash[3.0.0].jar       | None      |

[16:15:06] [main/FATAL]: The following problems were captured during this phase
[16:15:06] [main/ERROR]: Caught exception from botania (java.lang.IllegalAccessError: tried to access method net.minecraft.advancements.CriteriaTriggers.register(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger; from class vazkii.botania.common.Botania)
[16:15:06] [main/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 9/13/17 4:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania (botania)
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.advancements.CriteriaTriggers.register(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger; from class vazkii.botania.common.Botania
	at vazkii.botania.common.Botania.preInit(Botania.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.init(Minecraft.java:466)
	at net.minecraft.client.Minecraft.run(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 669275944 bytes (638 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2469 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                           | Signature |
	|:----- |:------------- |:------------ |:-------------------------------- |:--------- |
	| UCH   | minecraft     | 1.12.1       | minecraft.jar                    | None      |
	| UCH   | mcp           | 9.19         | minecraft.jar                    | None      |
	| UCH   | FML           | 8.0.99.99    | forgeBin-1.12.1-14.22.0.2469.jar | None      |
	| UCH   | forge         | 14.22.0.2469 | forgeBin-1.12.1-14.22.0.2469.jar | None      |
	| UCH   | baubles       | 1.5.1        | Baubles-1.12-1.5.1.jar           | None      |
	| UCE   | botania       | r1.10-347    | Botania r1.10-347-deobf.jar      | None      |
	| UCE   | botaniatweaks | 1.12-1.0.0   | bin                              | None      |
	| UCH   | backslash     | 1.12-3.0.0   | [1.12]BackSlash[3.0.0].jar       | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '3.3.0 - Build 8.15.10.2696' Renderer: 'Intel(R) HD Graphics 4000'
[16:15:06] [main/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\T902\Programming\Java\Minecraft\1.12\run\.\crash-reports\crash-2017-09-13_16.15.06-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by Tamaized** [comment]
I assume this is in a dev environment, wouldn't this then be on your end? Botania uses ATs for this.
https://github.com/Vazkii/Botania/blob/master/src/main/resources/META-INF/botania_at.cfg#L45

**Comment by williewillus** [comment]
Delete the build/ folder, rerun setupDW, and refresh the gradle project
