### ISSUE TITLE
Botania crashing game?. log included

### ISSUE THREAD

**Issue by Lancex93** [Vazkii/Botania#2387]
i have botania in my modback And what I can understand from crash logs, its causing my game to crash on start? im I correct?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.7-1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.7.jar)
  LoadingPlugin (Quark-r1.2-93b.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  AstralCore (astralsorcery-1.4.5.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/18/17 4:04 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:46)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_199_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:400)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:46)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_199_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:400)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 323819696 bytes (308 MB) / 722563072 bytes (689 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2476 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2476.jar) 
	UCH	forge{13.20.1.2476} [Minecraft Forge] (forge-1.11.2-13.20.1.2476.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	rpghud{3.6.6} [RPG-Hud] ([1.11] RPG-HUD-3.6.6.jar) 
	UCH	advancedcombat{1.0.1} [Advanced Combat] (advancedcombat-1.0.1-[1.11.2].jar) 
	UCH	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCH	quark{r1.2-93} [Quark] (Quark-r1.2-93b.jar) 
	UCH	animania{1.3} [Animania] (animania-1.11.2-1.3.jar) 
	UCH	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	baubles{1.4.6} [Baubles] (Baubles-1.11-1.4.6.jar) 
	UCH	bibliocraft{2.3.3} [BiblioCraft] (BiblioCraft[v2.3.3][MC1.11.2].jar) 
	UCH	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCH	botania{r1.9-345} [Botania] (Botania r1.9-345.jar) 
	UCH	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCH	chisel{MC1.11.2-0.0.14.25} [Chisel] (Chisel-MC1.11.2-0.0.14.25.jar) 
	UCH	cookingforblockheads{5.3.27} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.27.jar) 
	UCH	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2(21jul17).jar) 
	UCH	dungeontactics{DT-0.12.5} [DungeonTactics] (DungeonTactics-1.11.2-0.12.5.jar) 
	UCH	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.11.2.jar) 
	UCH	iceandfire{1.2.1} [Ice and Fire] (iceandfire-1.2.1.jar) 
	UCH	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCH	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCH	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.0.6-1.11.2.jar) 
	UCH	levels{r1.2.8} [Levels] (Levels 2-1.11.2-r1.2.8.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCH	xreliquary{1.11.2-1.3.4.678} [Reliquary] (Reliquary-1.11.2-1.3.4.678.jar) 
	UCH	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	runesofwizardry{1.11.2-0.8.2} [Runes of Wizardry] (Runes-of-Wizardry-1.11.2-0.8.2.jar) 
	UCH	runesofwizardry_classics{1.11.2-0.5.1-b1} [Runes of Wizardry - Classic Dusts Pack] (RunesofWizardry-Classics-1.11.2-0.5.1-b1.jar) 
	UCH	rustic{0.3.13} [Rustic] (rustic-0.3.13.jar) 
	UCH	shetiphiancore{3.4.7} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.7.jar) 
	UCH	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (StorageDrawers-1.11.2-4.2.10.jar) 
	UCH	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	UCH	terraqueous{1.3.15} [Terraqueous] (terraqueous-1.11.0-1.3.15.jar) 
	UCH	wearablebackpacks{2.5.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.5.0.jar) 
	UCH	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.7-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.7.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-93b.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon HD 8400 / R3 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Launched Version: 1.11.2-forge1.11.2-13.20.1.2476
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 8400 / R3 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-5200 APU with Radeon(TM) HD Graphics

**Comment by williewillus** [comment]
does this happen with botania alone? do you have any resource packs installed?

**Comment by FizzBuzz3000** [comment]
So I decided to remove all mods since I was getting this error in 1.12.1 w/ the latest botania release and I found the problem: It's Chisel! As to why, I've not a clue. So for now remove chisel and be on your merry way.

**Comment by bloodmc** [comment]
This isn't a botania issue. Chisel requires CTM (https://minecraft.curseforge.com/projects/ctm)
Install that and you won't get a crash.

**Comment by codycoolwaffle** [comment]
If the issue is resolved, can we get this closed?
