### ISSUE TITLE
Botania crashes with Chisel installed (1.12.1, Botania 1.10-r347)

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#2388]
So with botania-1.10-r347 and Chisel-MC1.12-0.0.14.18, the following NPE crash occurs:
```
[20:56:08] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ModelBakeEvent@1545b9da:
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42) ~[GunModel.class:?]
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95) ~[MiscellaneousIcons.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[20:56:08] [main/ERROR] [FML]: Index: 1 Listeners:
[20:56:08] [main/ERROR] [FML]: 0: NORMAL
[20:56:08] [main/ERROR] [FML]: 1: ASM: vazkii.botania.client.core.handler.MiscellaneousIcons@46c09751 onModelBake(Lnet/minecraftforge/client/event/ModelBakeEvent;)V
```

The attached log ONLY has botania, chisel, and baubles active.
[fml-client-latest.txt](https://github.com/Vazkii/Botania/files/1312822/fml-client-latest.txt)

**Comment by accessdenied0** [comment]
To notice here: It doesn't crash with the [_Connected Texture Manager Lib_ (short CTM-Lib).](https://minecraft.curseforge.com/projects/ctmlib)

I use CTM-MC1.12-0.2.2.7.

**Comment by williewillus** [comment]
^
