### ISSUE TITLE
Botania crash when creating a new world

### ISSUE THREAD

**Issue by Sethgoldfox** [Vazkii/Botania#250]
My game crashes when I go to create a new world. The Crash Report mentions Botania and Baubles. I got this crash when I updated Forge to "forge-1.7.10-10.13.0.1197-universal" And then I replicated the crash with "forge-1.7.10-10.13.0.1207-universal". I was upgrading from "forge-1.7.10-10.13.0.1187-universal". I upgraded because COFHcore and Thermal Expansion needed a newer forge version to run.

FML Log: http://puu.sh/aX5Iz/f8b26c0a81.log

**Comment by alpharulesirulee** [comment]
HELP I GOT THE SAME THING

 Unreported exception thrown!
java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
	at vazkii.botania.client.core.handler.HUDHandler.onDrawScreen(HUDHandler.java:100) ~[HUDHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_259_HUDHandler_onDrawScreen_Post.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: baubles.common.lib.PlayerHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 16 more

**Comment by Vazkii** [comment]
Wow necropost ahoy. You didn't install baubles. And update your botania.

**Comment by alpharulesirulee** [comment]
never mind i deleted it

**Comment by alpharulesirulee** [comment]
led to a ticking player crash

**Comment by alpharulesirulee** [comment]
i fixed it
