### ISSUE TITLE
NullPointerException: Initializing game

### ISSUE THREAD

**Issue by mcenderdragon** [Vazkii/Botania#2577]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.3.0-61.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  FMLPlugin (albedo-0.1.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/8/18 12:08 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_518_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:42)
	at vazkii.botania.client.core.handler.MiscellaneousIcons.onModelBake(MiscellaneousIcons.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_518_MiscellaneousIcons_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 287388896 bytes (274 MB) / 1082085376 bytes (1031 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                        | Signature                                |
	|:----- |:----------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCH   | mcp                     | 9.42              | minecraft.jar                                 | None                                     |
	| UCH   | FML                     | 8.0.99.99         | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.2.2624      | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | advancedrocketrycore    | 1                 | minecraft.jar                                 | None                                     |
	| UCH   | albedocore              | 0.1               | minecraft.jar                                 | None                                     |
	| UCH   | libvulpes               | 0.2.8.-27         | LibVulpes-1.12.2-0.2.8-27-universal.jar       | None                                     |
	| UCH   | advancedrocketry        | 1.3.0.-61         | AdvancedRocketry-1.12.2-1.3.0-61.jar          | None                                     |
	| UCH   | infinitylib             | 1.12.2-1.12.0     | infinitylib-1.12.0.jar                        | None                                     |
	| UCH   | agricraft               | 2.12.0-1.12.0-a1  | agricraft-2.12.0-1.12.0-a1.jar                | None                                     |
	| UCH   | albedo                  | 0.1.3             | albedo-0.1.3.jar                              | None                                     |
	| UCH   | applecore               | 3.1.1             | AppleCore-mc1.12.2-3.1.1.jar                  | None                                     |
	| UCH   | psi                     | r1.1-59           | Psi-r1.1-59.jar                               | None                                     |
	| UCH   | autoreglib              | 1.3-15            | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCH   | baubles                 | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCH   | bdlib                   | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| UCH   | bibliotheca             | 1.2.2-1.12.2      | bibliotheca-1.2.2-1.12.2.jar                  | None                                     |
	| UCH   | charset                 | 0.5.0.199         | Charset-Lib-0.5.0.199.jar                     | None                                     |
	| UCH   | jei                     | 4.8.5.159         | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCH   | forestry                | 5.8.0.250         | forestry_1.12.2-5.8.0.250.jar                 | None                                     |
	| UCH   | binniecore              | unspecified       | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | binniedesign            | 1.0               | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | genetics                | 2.5.0.112         | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | botany                  | 2.5.0.112         | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | extrabees               | 2.5.0.112         | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | extratrees              | 2.5.0.112         | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCH   | guideapi                | 1.12-2.1.4-57     | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UCH   | bloodmagic              | 1.12.2-2.2.7-90   | BloodMagic-1.12.2-2.2.7-90.jar                | None                                     |
	| UCH   | bookshelf               | 2.3.533           | Bookshelf-1.12.2-2.3.533.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | botania                 | r1.10-353         | Botania+r1.10-353.jar                         | None                                     |
	| UCH   | careerbees              | 1.0               | careerbees-0.4.0.jar                          | None                                     |
	| UCH   | chisel                  | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                  | None                                     |
	| UCH   | mantle                  | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCH   | tconstruct              | 1.12.2-2.9.1.65   | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCH   | ceramics                | 1.12-1.3.3b       | Ceramics-1.12-1.3.3b.jar                      | None                                     |
	| UCH   | codechickenlib          | 3.1.5.331         | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chickenchunks           | 2.4.1.71          | ChickenChunks-1.12.2-2.4.1.71-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chiselsandbits          | 14.14             | chiselsandbits-14.14.jar                      | None                                     |
	| UCH   | extendedrenderer        | v1.0              | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCH   | coroutil                | 1.12.1-1.1.24     | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCH   | configmod               | v1.0              | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCH   | enderstorage            | 2.4.2.126         | EnderStorage-1.12.2-2.4.2.126-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | engineersworkshop       | 1.4.0-1.12.2      | EngineersWorkshop-1.4.0-1.12.2.jar            | None                                     |
	| UCH   | factorytech             | 1.1.5             | FactoryTech-1.12.2-1.3.7.jar                  | None                                     |
	| UCH   | fastleafdecay           | v14               | FastLeafDecay-v14.jar                         | None                                     |
	| UCH   | redstoneflux            | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | sonarcore               | 5.0.6             | sonarcore-1.12.2-5.0.6.jar                    | None                                     |
	| UCH   | fluxnetworks            | 3.0.5             | fluxnetworks-1.12.2-3.0.5.jar                 | None                                     |
	| UCH   | forgelin                | 1.6.0             | Forgelin-1.6.0.jar                            | None                                     |
	| UCH   | ichunutil               | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCH   | ftblib                  | 5.0.0.8           | FTBLib-5.0.0.9.jar                            | None                                     |
	| UCH   | fp                      | 26.3.123          | Futurepack-1.12.2-26.3.123.jar                | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| UCH   | fp.api                  | 1.1.0             | Futurepack-1.12.2-26.3.123.jar                | None                                     |
	| UCH   | gendustry               | 1.6.5.8           | gendustry-1.6.5.8-mc1.12.2.jar                | None                                     |
	| UCH   | advgenerators           | 0.9.20.12         | generators-0.9.20.12-mc1.12.2.jar             | None                                     |
	| UCH   | googlyeyes              | 7.0.2             | GooglyEyes-1.12.2-7.0.2.jar                   | None                                     |
	| UCH   | gravestone              | 1.10.1            | gravestone-1.10.1.jar                         | None                                     |
	| UCH   | gravitygun              | 7.0.0             | GravityGun-1.12.2-7.0.1.jar                   | None                                     |
	| UCH   | gbook                   | 2.0.1             | Guidebook-1.12.2-2.0.1.jar                    | None                                     |
	| UCH   | teslacorelib            | 1.0.13            | tesla-core-lib-1.12-1.0.13.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing     | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.8.4-124.jar      | None                                     |
	| UCH   | ironbackpacks           | 1.12.2-3.0.5-6    | IronBackpacks-1.12.2-3.0.5-6.jar              | None                                     |
	| UCH   | ironchest               | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar               | None                                     |
	| UCH   | jeibees                 | 0.9.0.5           | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UCH   | jeiintegration          | 1.5.1.36          | jeiintegration_1.12.2-1.5.1.36.jar            | None                                     |
	| UCH   | longfallboots           | 1.2.1a            | longfallboots-1.2.1a.jar                      | None                                     |
	| UCH   | mobamputation           | 7.0.0             | MobAmputation-1.12.2-7.0.0.jar                | None                                     |
	| UCH   | mobdismemberment        | 7.0.0             | MobDismemberment-1.12.2-7.0.0.jar             | None                                     |
	| UCH   | morpheus                | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UCH   | neat                    | 1.4-15            | Neat+1.4-15.jar                               | None                                     |
	| UCH   | nuclearcraft            | 2.9d              | NuclearCraft-2.9d--1.12.2.jar                 | None                                     |
	| UCH   | portalgun               | 7.0.2             | PortalGun-1.12.2-7.0.2.jar                    | None                                     |
	| UCH   | reborncore              | 3.6.9.216         | RebornCore-1.12.2-3.6.9.216-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | quantumstorage          | 4.4.8             | QuantumStorage-1.12-4.4.8.jar                 | None                                     |
	| UCH   | refinedstorage          | 1.5.31            | refinedstorage-1.5.31.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | refinedstorageaddons    | 0.2               | refinedstorageaddons-0.2.jar                  | None                                     |
	| UCH   | xreliquary              | 1.12.2-1.3.4.757  | Reliquary-1.12.2-1.3.4.757.jar                | None                                     |
	| UCH   | rockhounding_core       | 3.06              | rockhounding_core-1.12.2-3.06.jar             | None                                     |
	| UCH   | rockhounding_chemistry  | 1.12.2-3.04       | rockhounding_chemistry-1.12.2-3.04.jar        | None                                     |
	| UCH   | rustic                  | 1.0.0             | rustic-1.0.0.jar                              | None                                     |
	| UCH   | shearmadness            | 1.12.1            | shearmadness-1.12.1-1.7.0.3.jar               | None                                     |
	| UCH   | valkyrielib             | 1.12.2-2.0.8a     | valkyrielib-1.12.2-2.0.8a.jar                 | None                                     |
	| UCH   | simplegenerators        | 1.12.2-2.0.8a     | simplegenerators-1.12.2-2.0.8a.jar            | None                                     |
	| UCH   | simplelogic             | 0.5.0.199         | SimpleLogic-0.5.0.199.jar                     | None                                     |
	| UCH   | spiceoflife             | 1.3.11            | SpiceOfLife-mc1.12-1.3.11.jar                 | None                                     |
	| UCH   | stevescarts             | 2.4.17.88         | StevesCarts-1.12.2-2.4.17.88.jar              | None                                     |
	| UCH   | tinker_io               | release 2.6.1     | tinker_io-1.12.2-release+2.6.1.jar            | None                                     |
	| UCH   | tcomplement             | ${version}        | TinkersComplement-1.12.1-0.2.2b.jar           | None                                     |
	| UCH   | totemic                 | 1.12.2-0.10.2     | Totemic-1.12.2-0.10.2.jar                     | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UCH   | wawla                   | 2.5.251           | Wawla-1.12.2-2.5.251.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | waystones               | 4.0.20            | Waystones_1.12.2-4.0.20.jar                   | None                                     |
	| UCH   | yabba                   | 1.1.0.5           | YABBA-1.1.0.6.jar                             | None                                     |
	| UCH   | zettaindustries         | 1.3               | zettaindustries-1.3-1.12.2-155.jar            | None                                     |
	| UCH   | teslacorelib_registries | 1.0.13            | tesla-core-lib-1.12-1.0.13.jar                | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.3.0-61.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
FMLPlugin (albedo-0.1.3.jar)
  elucent.albedo.asm.ASMTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.73' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	List of loaded APIs: 
		* AgriCraftAPI (1.0) from agricraft-2.12.0-1.12.0-a1.jar
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.1.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.2.7-90.jar
		* BotaniaAPI (89) from Botania+r1.10-353.jar
		* CharsetAPI (0.1) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Audio (0.0) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Carry (0.0) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Laser (0.0) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Lib (0.2) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Locks (0.1) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Pipes (0.3) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Storage (0.1) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Tape (0.0) from Charset-Lib-0.5.0.199.jar
		* CharsetAPI|Wires (0.3) from Charset-Lib-0.5.0.199.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.14.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.12.1-1.1.24.jar
		* fluxapi (1.0) from fluxnetworks-1.12.2-3.0.5.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.250.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.4-57.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.8.4-124.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.159.jar
		* PsiAPI (6) from Psi-r1.1-59.jar
		* reborncoreAPI (3.6.9.216) from RebornCore-1.12.2-3.6.9.216-universal.jar
		* reborncoreAPI|Power (3.6.9.216) from RebornCore-1.12.2-3.6.9.216-universal.jar
		* reborncoreAPI|Recipe (3.6.9.216) from RebornCore-1.12.2-3.6.9.216-universal.jar
		* reborncoreAPI|Tile (3.6.9.216) from RebornCore-1.12.2-3.6.9.216-universal.jar
		* rh_api (3.00) from rockhounding_core-1.12.2-3.06.jar
		* shearmadness.api (@API_VERSION@) from shearmadness-1.12.1-1.7.0.3.jar
		* shearmadness_api_plumbing (1.0) from shearmadness-1.12.1-1.7.0.3.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.6.jar
		* stevescartsAPI (${version}) from StevesCarts-1.12.2-2.4.17.88.jar
		* stevescartsAPI|FARMS (${version}) from StevesCarts-1.12.2-2.4.17.88.jar
		* totemic|API (1.12.2-6.2.0) from Totemic-1.12.2-0.10.2.jar
		* valkyrielib.api (1.12-2.0.1a) from valkyrielib-1.12.2-2.0.8a.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.9.216
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2624
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.73, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
```

**Comment by mcenderdragon** [comment]
This happens when starting the game.

**Comment by brainiac744** [comment]
Chisel - probably missingCTM
#2387
