### ISSUE TITLE
Crash on placing abstruse platform, and further crashes on world load

### ISSUE THREAD

**Issue by Jesse-Goertzen** [Vazkii/Botania#3204]
# Version Information
Forge version:  forge-28.1.117
Botania version:  Botania r1.11-378

# Further Information
Link to crash log: [Crashlog](https://gist.github.com/Jesse-Goertzen/fd51b3de5790a10f9ea648f0e324e52c)
Steps to reproduce:
1. Placed abstruse platform
2. Crash
3. Crash on world load

I am using Optifine, but it still crashes with the same error even if Optifine is removed.

**Comment by williewillus** [comment]
```
at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
```
can you try without those mods?

**Comment by Jesse-Goertzen** [comment]
Oh jeez. I read the log last night but clearly I missed those lines. Yes, removing Better Foliage fixed the issue. Thank you for your time helping me with reading comprehension
