### ISSUE TITLE
"Air item cannot be cast to vazkii.botania.common.item"

### ISSUE THREAD

**Issue by Benjamboo** [Vazkii/Botania#3360]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/23/20 10:21 PM
Description: Ticking player

java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to vazkii.botania.common.item.equipment.bauble.ItemBauble
	at vazkii.botania.common.core.handler.EquipmentHandler$InventoryEquipmentHandler.onPlayerTick(EquipmentHandler.java:108) ~[?:1.16-394] {re:classloading}
	at vazkii.botania.common.core.handler.EquipmentHandler$$Lambda$7221/1037224059.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2778/1316317287.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:195) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches PlayerEntity Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:393) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:194) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$9750/844429463.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at vazkii.botania.common.core.handler.EquipmentHandler$InventoryEquipmentHandler.onPlayerTick(EquipmentHandler.java:108)
	at vazkii.botania.common.core.handler.EquipmentHandler$$Lambda$7221/1037224059.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2778/1316317287.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:195)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 146
	Entity Name: BenJammmm
	Entity's Exact location: -1652.20, 68.00, -916.22
	Entity's Block location: World: (-1653,68,-917), Chunk: (at 11,4,11 in -104,-58; contains blocks -1664,0,-928 to -1649,255,-913), Region: (-4,-2; contains chunks -128,-64 to -97,-33, blocks -2048,0,-1024 to -1537,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:393)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:194)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at net.minecraft.server.MinecraftServer$$Lambda$9750/844429463.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1489338240 bytes (1420 MB) / 3655860224 bytes (3486 MB) up to 6912212992 bytes (6592 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7416m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.75.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.75-client.jar Minecraft {minecraft@1.16.1 DONE}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		ClientTweaks_1.16.1-5.0.0.jar Client Tweaks {clienttweaks@5.0.0 DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		ImmersiveEngineering-0.16-109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
		BiomesOPlenty-1.16.1-11.0.0.390-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.390 DONE}
		MekanismAdditions-1.16.1-10.0.3.426.jar Mekanism: Additions {mekanismadditions@10.0.3 DONE}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		Ding-1.16.1-1.1.0.jar Ding {ding@1.1.0 DONE}
		Botania-1.16-394.jar Botania {botania@1.16-394 DONE}
		Mekanism-1.16.1-10.0.3.426.jar Mekanism {mekanism@10.0.3 DONE}
		modnametooltip_1.16.1-1.14.0.jar Mod Name Tooltip {modnametooltip@1.14.0 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		pamhc2foodcore-1.16.1-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 DONE}
		flourpower-1.16.1-1.1.4.jar Flour Power {flourpower@1.16.1-1.1.4 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		FastWorkbench-1.16.1-4.1.1.jar FastWorkbench {fastbench@4.1.1 DONE}
		CTM-MC1.16.1-1.1.0.1.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.0.1 DONE}
		CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		Placebo-1.16.1-4.0.1.jar Placebo {placebo@4.0.1 DONE}
		comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 DONE}
		AutoRegLib-1.6-42.jar AutoRegLib {autoreglib@1.6-42 DONE}
		DoubleSlabs-1.16-3.2.0.jar Double Slabs {doubleslabs@3.2.0 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		FarmingForBlockheads_1.16.1-7.0.1.jar Farming for Blockheads {farmingforblockheads@7.0.1 DONE}
		Bookshelf-1.16.1-6.1.11.jar Bookshelf {bookshelf@6.1.11 DONE}
		randompatches-1.16.1-1.22.0.0.jar RandomPatches {randompatches@1.16.1-1.22.0.0 DONE}
		discordrpc-2.0.4-1.16.jar DiscordRichPresence {discordrpc@2.0.4 DONE}
		MekanismTools-1.16.1-10.0.3.426.jar Mekanism: Tools {mekanismtools@10.0.3 DONE}
		FastFurnace-1.16.1-4.0.0.jar FastFurnace {fastfurnace@4.0.0 DONE}
		ForgivingVoid_1.16.1-5.0.0.jar Forgiving Void {forgivingvoid@5.0.0 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		engineersdecor-1.16.1-1.1.1-b3.jar Engineer's Decor {engineersdecor@1.1.1-b3 DONE}
		MekanismGenerators-1.16.1-10.0.3.426.jar Mekanism: Generators {mekanismgenerators@10.0.3 DONE}
		JustEnoughResources-1.16.1-0.11.0.79.jar Just Enough Resources {jeresources@0.11.0.79 DONE}
		forgemod_VoxelMap-1.10.6b_for_1.16.1.jar VoxelMap {voxelmap@1.10.6 DONE}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 DONE}
		Quark-r2.2-254.jar Quark {quark@r2.2-254 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.1-12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['BenJammmm'/146, l='ServerLevel[Techworld]', x=-1652.20, y=68.00, z=-916.22]]
	Data Packs: vanilla, mod:appleskin, mod:autoreglib (incompatible), mod:biomesoplenty, mod:botania, mod:clienttweaks (incompatible), mod:collective, mod:comforts (incompatible), mod:cookingforblockheads (incompatible), mod:craftingtweaks (incompatible), mod:ctm, mod:ding, mod:discordrpc (incompatible), mod:doubleslabs, mod:elevatorid, mod:engineersdecor, mod:farmingforblockheads (incompatible), mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:flourpower, mod:forge, mod:forgivingvoid (incompatible), mod:gravestone, mod:ironchest, mod:jei (incompatible), mod:mcwbridges, mod:mcwdoors, mod:mekanism, mod:mekanismadditions, mod:mekanismgenerators, mod:mekanismtools, mod:modnametooltip (incompatible), mod:mousetweaks (incompatible), mod:netherportalfix (incompatible), mod:pamhc2foodcore (incompatible), mod:patchouli (incompatible), mod:placebo (incompatible), mod:quark, mod:valhelsia_structures (incompatible), mod:voxelmap, mod:waystones (incompatible), mod:bookshelf (incompatible), mod:randompatches (incompatible), mod:refinedstorage, mod:immersiveengineering (incompatible), mod:jeresources (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by williewillus** [comment]
any information about what was going on at the time?

**Comment by Benjamboo** [comment]
Sorry, not much of a coder so I jusy copy-pasted the crash log

This happened when I made a band of Mana on Sunday, I just put the game down for the night and came back today and it's still crashing.  (I thought it was a one off CTD, not going to be a consistent one. ah well.)
