### ISSUE TITLE
Config handler calls client side method

### ISSUE THREAD

**Issue by Sir-Will** [Vazkii/Botania#3446]
# Version Information
Forge version:  forge-1.16.1-32.0.108
Botania version:  Botania-1.16.1-403.jar

# Further Information
Botania seems to call a method which is only available on the client during the server startup.

```
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at java.lang.reflect.Method.invoke(Method.java:498)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       ... 7 more
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at vazkii.botania.common.core.handler.ConfigHandler$Common.lambda$new$0(ConfigHandler.java:232)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.common.ForgeConfigSpec$Builder.lambda$defineList$5(ForgeConfigSpec.java:317)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.common.ForgeConfigSpec$ValueSpec.test(ForgeConfigSpec.java:680)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:191)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.common.ForgeConfigSpec.isCorrect(ForgeConfigSpec.java:121)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.common.ForgeConfigSpec.setConfig(ForgeConfigSpec.java:84)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.config.ModConfig.setConfigData(ModConfig.java:86)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:105)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.lang.Iterable.forEach(Iterable.java:75)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:50)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraft.server.Main.main(Main.java:95)
[21:58:48] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    ... 13 more

```

**Comment by Sir-Will** [comment]
Nvm, seems to be fixed in 403.1
