### ISSUE TITLE
Crash when inserting unstackable items into an inventory with corporea on Fabric

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#4022]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-432-FABRIC-SNAPSHOT

### Modloader version

fabricLoaderVersion=0.13.3 fabricApiVersion=0.50.0+1.18.2

### Modpack info

Incorporeal 3 dev instance

### The latest.log file

In description

### Issue description

1. build this 
![image](https://user-images.githubusercontent.com/2068021/164385851-195b49d8-ae28-425a-bc63-b113726601aa.png)
2. press button
3.

```console
[02:09:21] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5fe84ea, suppressing error
 net.minecraft.ReportedException: Exception while updating neighbours
	at net.minecraft.world.level.Level.neighborChanged(Level.java:371) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.Level.updateNeighborsAt(Level.java:325) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:1377) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:235) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:196) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.block.ButtonBlock.press(ButtonBlock.java:117) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.block.ButtonBlock.use(ButtonBlock.java:110) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:939) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:336) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1081) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:30) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:22) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:157) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:808) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:165) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:131) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:790) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:784) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:140) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:769) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:273) ~[minecraft-project-@Fabric-mapped.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Transfer variant may not be blank.
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39) ~[fabric-transfer-api-v1-1.6.0+2373a54560.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58) ~[fabric-transfer-api-v1-1.6.0+2373a54560.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.insert(SingleStackStorage.java:108) ~[fabric-transfer-api-v1-1.6.0+2373a54560.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.insert(SingleStackStorage.java:42) ~[fabric-transfer-api-v1-1.6.0+2373a54560.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:67) ~[fabric-transfer-api-v1-1.6.0+2373a54560.jar:?]
	at vazkii.botania.fabric.xplat.FabricXplatImpl.insertToInventory(FabricXplatImpl.java:325) ~[Botania-1.18.2-432-FABRIC-SNAPSHOT.jar:?]
	at vazkii.botania.common.block.tile.corporea.TileCorporeaFunnel.doCorporeaRequest(TileCorporeaFunnel.java:84) ~[Botania-1.18.2-432-FABRIC-SNAPSHOT.jar:?]
	at vazkii.botania.common.block.tile.corporea.TileCorporeaFunnel.doRequest(TileCorporeaFunnel.java:45) ~[Botania-1.18.2-432-FABRIC-SNAPSHOT.jar:?]
	at vazkii.botania.common.block.corporea.BlockCorporeaFunnel.neighborChanged(BlockCorporeaFunnel.java:44) ~[Botania-1.18.2-432-FABRIC-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.neighborChanged(BlockBehaviour.java:884) ~[minecraft-project-@Fabric-mapped.jar:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:356) ~[minecraft-project-@Fabric-mapped.jar:?]
	... 25 more
```

### Other information

Actually crashes instead of stacktracing if the redstone wasn't triggered by the player

**Comment by quat1024** [comment]
debugging: inserting a println at the start of `TileCorporeaFunnel#doCorporeaRequest`:
```java
System.out.println("Got ItemStacks: " + stacks.stream().map(ItemStack::toString).collect(Collectors.joining(", ")));
```
stackable items print something like `Got ItemStacks: 8 andesite, 8 andesite`
unstackables print something like `Got ItemStacks: 1 diamond_sword, 0 air`
