### ISSUE TITLE
Unexpected Crash (Could also be caused by trinkets?)

### ISSUE THREAD

**Issue by HacoKavanah** [Vazkii/Botania#4027]
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

 Botania-1.18.2-431-FABRIC.jar

### Modloader version

Fabric 0.13.3 -  fabric-api-0.51.1+1.18.2.jar

### Modpack info

Private Custom Modpack

### The latest.log file

-

### Issue description

Got it suddenly by moving at high speeds. No clue how to reproduce.

[13:10:45] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1792.method_40131()" because the return value of "net.minecraft.class_1799.method_7909()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at net.minecraft.item.ItemStack.isIn(ItemStack:230) ~[?:?]
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.lambda$hasMonocle$2(ItemMonocle.java:102) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.lambda$getEquipped$2(LivingEntityTrinketComponent.java:322) ~[trinkets-3.3.0.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:335) ~[trinkets-3.3.0.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.getEquipped(LivingEntityTrinketComponent.java:321) ~[trinkets-3.3.0.jar:?]
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.lambda$findItem$3(TrinketsIntegration.java:88) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.findItem(TrinketsIntegration.java:87) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at vazkii.botania.common.handler.EquipmentHandler.findOrEmpty(EquipmentHandler.java:51) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.hasMonocle(ItemMonocle.java:99) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at vazkii.botania.client.gui.HUDHandler.onDrawScreenPost(HUDHandler.java:155) ~[Botania-1.18.2-431-FABRIC.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-1.10.7+54e5b2ec60-970875427b51c59c.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$dee001$render(InGameHud:8029) ~[?:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:415) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[13:10:45] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Omistaja\Documents\curseforge\minecraft\Instances\Essential Beginnings (1)\crash-reports\crash-2022-04-25_13.10.45-client.txt

Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1792.method_40131()" because the return value of "net.minecraft.class_1799.method_7909()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at net.minecraft.item.ItemStack.isIn(ItemStack:230)
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.lambda$hasMonocle$2(ItemMonocle.java:102)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.lambda$getEquipped$2(LivingEntityTrinketComponent.java:322)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:335)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.getEquipped(LivingEntityTrinketComponent.java:321)
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.lambda$findItem$3(TrinketsIntegration.java:88)
	at java.util.Optional.flatMap(Optional.java:289)
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.findItem(TrinketsIntegration.java:87)
	at vazkii.botania.common.handler.EquipmentHandler.findOrEmpty(EquipmentHandler.java:51)
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.hasMonocle(ItemMonocle.java:99)
	at vazkii.botania.client.gui.HUDHandler.onDrawScreenPost(HUDHandler.java:155)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.client.gui.hud.InGameHud.handler$dee001$render(InGameHud:8029)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:415)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1799.method_31573(class_1799.java:230)
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.lambda$hasMonocle$2(ItemMonocle.java:102)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.lambda$getEquipped$2(LivingEntityTrinketComponent.java:322)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:335)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.getEquipped(LivingEntityTrinketComponent.java:321)
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.lambda$findItem$3(TrinketsIntegration.java:88)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at vazkii.botania.fabric.integration.trinkets.TrinketsIntegration.findItem(TrinketsIntegration.java:87)
	at vazkii.botania.common.handler.EquipmentHandler.findOrEmpty(EquipmentHandler.java:51)
	at vazkii.botania.common.item.equipment.bauble.ItemMonocle.hasMonocle(ItemMonocle.java:99)
	at vazkii.botania.client.gui.HUDHandler.onDrawScreenPost(HUDHandler.java:155)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$dee001$render(class_329.java:8029)
	at net.minecraft.class_329.method_1753(class_329.java:415)

**Comment by williewillus** [comment]
@emilyploszaj any idea here? Looks like the guts of TrinketComponent are passing a null stack to our predicate that we pass to `getEquipped`

**Comment by Dragon-Seeker** [comment]
@HacoKavanah Can you send the mod list?

**Comment by Emmanuel-cangy** [comment]
Hey ! I also came into a similar error and currently looking for a fix cause it seems some people have similar issues due to botania. @Dragon-Seeker 
here is my crash file.
[crash-2022-10-22_12.01.09-client.txt](https://github.com/VazkiiMods/Botania/files/9843894/crash-2022-10-22_12.01.09-client.txt)

**Comment by TheRealWormbo** [comment]
Closing this now, since we have not seen similar reports for newer versions, and 1.18 is definitely no longer supported.
