### ISSUE TITLE
Can't revive back to spawn after suicide

### ISSUE THREAD

**Issue by 106umao** [Vazkii/Botania#4045]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

forge 39.1.2

### Modpack info

none

### The latest.log file

https://gist.github.com/106umao/5d71c2a9314cd00e749a8be850410b31

### Issue description

Can't revive back to spawn after suicide

### Steps to reproduce

run command `suicide`

### Other information

There is too much content in the latest.log file, I think the location of the bug is in these contents of the log file:
```
         at TRANSFORMER/botania@1.18.1-429/vazkii.botania.forge.xplat.ForgeXplatImpl.keptItemsComponent(ForgeXplatImpl.java:281)
         at TRANSFORMER/botania@1.18.1-429/vazkii.botania.common.item.ItemKeepIvy.onPlayerRespawn(ItemKeepIvy.java:55)
         at TRANSFORMER/botania@1.18.1-429/vazkii.botania.forge.ForgeCommonInitializer.lambda$registerEvents$21(ForgeCommonInitializer.java:297)
```
Hope it will help you

**Comment by williewillus** [comment]
Please update your Botania version, this was fixed
