### ISSUE TITLE
Crash on displaying a planned mana enchanter

### ISSUE THREAD

**Issue by gchpaco** [Vazkii/Botania#4055]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-432

### Modloader version

40.1.25

### The latest.log file

https://gist.github.com/gchpaco/f7c8708130699c2b9336fdd6a4d02c5e

### Issue description

Exiting a door with the Lexica Botania set to plan for mana enchanting and it crashed.

**Comment by williewillus** [comment]
Does it happen every time? and does it happen with just botania and its dependencies?

**Comment by gchpaco** [comment]
It does appear to happen every time I try to display the mana enchanter; that is, I just tried to, using the lexica botania, create ghost images for the mana enchanter, and it crashed again with the following log output.

https://gist.github.com/gchpaco/ecf1f35eb4550a7cf50f18fac89b00c0

In particular, I noticed these, which I've truncated; you can see the full stacktrace in the log:
```
[01Jun.2022 00:40:34.627] [Render thread/WARN] [botania/]: Failed to render lexicon
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.getString()" because the return value of "vazkii.botania.common.item.ItemLexicon.getTitle(net.minecraft.world.item.ItemStack)" is null
	at vazkii.botania.client.core.handler.RenderLexicon.doRender(RenderLexicon.java:142) ~[Botania-1.18.2-432.jar%2380!/:1.18.2-432]
	at vazkii.botania.client.core.handler.RenderLexicon.renderHand(RenderLexicon.java:84) ~[Botania-1.18.2-432.jar%2380!/:1.18.2-432]
```
and
```
[01Jun.2022 00:40:34.801] [Render thread/WARN] [botania/]: Failed to render lexicon
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.getString()" because the return value of "vazkii.botania.common.item.ItemLexicon.getTitle(net.minecraft.world.item.ItemStack)" is null
	at vazkii.botania.client.core.handler.RenderLexicon.doRender(RenderLexicon.java:142) ~[Botania-1.18.2-432.jar%2380!/:1.18.2-432]
	at vazkii.botania.client.core.handler.RenderLexicon.renderHand(RenderLexicon.java:84) ~[Botania-1.18.2-432.jar%2380!/:1.18.2-432]
```
I'm not sure if this is relevant or not.

**Comment by gchpaco** [comment]
I haven't had this problem with *other* ghost blocks with Patchouli mods, just this one.

**Comment by perfectlyGray** [comment]
im having the same problem, im in direwolf20 1.18 v1.6.1
botania is 1.18.2-433
here is the crash log https://pastebin.com/D6DbpRuB
