### ISSUE TITLE
CME startup crash

### ISSUE THREAD

**Issue by ukmcplyr** [Vazkii/Botania#4409]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Forge 1.19.2-43.2.14

### The latest.log file

https://pste.ch/jewoxihuya.pl

### Issue description

Hit the following CME a short while ago on an in-dev modpack:

```
[22/06/2023 18:37:28 pm] java.util.ConcurrentModificationException: null
[22/06/2023 18:37:28 pm] 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
[22/06/2023 18:37:28 pm] 	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?] {}
[22/06/2023 18:37:28 pm] 	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?] {}
[22/06/2023 18:37:28 pm] 	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$1.next(Collections.java:1711) ~[?:?] {}
[22/06/2023 18:37:28 pm] 	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$1.next(Collections.java:1704) ~[?:?] {}
[22/06/2023 18:37:28 pm] 	at vazkii.botania.forge.client.ForgeFloatingFlowerModel.getMaterials(ForgeFloatingFlowerModel.java:55) ~[Botania-1.19.2-440-FORGE.jar%23515!/:1.19.2-440-FORGE] {re:classloading}
[...]
```

### Other information

Hopefully I've gotten the right culprit.  Crash log [here](https://pste.ch/isukabexap.pl) in case it's helpful and full mod list [here](https://pste.ch/modufumexu.css).

Only hit this once in around 50 boots so I'm not sure how easily reproduceable it is, if at all.

**Comment by williewillus** [comment]
can you get it to happen with just botania?

**Comment by ukmcplyr** [comment]
I'll give that a try and report back :+1:

**Comment by ukmcplyr** [comment]
Bah. I can't reproduce with either just Botania or Botania plus Applied Botanics / Botanic Additions. I Should've tried that first, apologies.

Not the best with low-level java/forge. I'm guessing this means the bad interaction/missing synchronisation is much more likely to be in another mod?

**Comment by williewillus** [comment]
yeah, in that case you'll have to hunt it down or do a binary search, sorry.
