### ISSUE TITLE
NEI Issues

### ISSUE THREAD

**Issue by O13SC3N3** [Vazkii/Botania#732]
Useally Happens when you look at an NEI item/recipe the FIRST TIME. Second time useally results in no issues. Causes seem to be using Tinker's Construct Crafting Station, and looking up other Modded Recipes, Not in a crafting GUI already, looking up the recipe the first time. We tested to see if it was jus modded Recipes, but a few randomly supported Mods, and Vanilla items will do it randomly.

NEI 1.0.4.90, NEIIntregration 1.0.7, NEI Addons 1.12.5.17
 Forge 1291, Java 8, Custom Modpack, Minecraft 1.7.10

Forwarded to NEI, NEI Addons (Closed), NEI Integration.

java.lang.NullPointerException: Updating screen events
 at vazkii.botania.client.integration.nei.RecipeHandlerPetalApothecary.loadCraftingRecipes(RecipeHandlerPetalApothecary.java:121)
 at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
 at vazkii.botania.client.integration.nei.RecipeHandlerPetalApothecary.loadCraftingRecipes(RecipeHandlerPetalApothecary.java:115)
 at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
 at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
 at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
 at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
 at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
 at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
 at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
 at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
 at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
 at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
 at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Vazkii** [comment]
Need the whole log. Do you have any tweaked recipes?

**Comment by O13SC3N3** [comment]
http://pastebin.com/raw.php?i=N7gACnWw

**Comment by O13SC3N3** [comment]
And this Ticking Entity Crash appeared, been trying to track it down to purge the chunk or entities. It mentions Botania items causing damage. http://pastebin.com/raw.php?i=iGcZ6MpD

**Comment by Vazkii** [comment]
I'll quote what Forestry has in that log.
>Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by O13SC3N3** [comment]
I apologize but the server is only using Forge version. No Bukkit, no Spigot, or Cauldron.

**Comment by Vazkii** [comment]
Uh huh.

>  Server brand: cauldron,craftbukkit,mcpc,fml,forge

>  Server brand: cauldron,craftbukkit,mcpc,fml,forge

**Comment by O13SC3N3** [comment]
Apologies, I've asked the server host and was only told forge.

**Comment by Vazkii** [comment]
So does the issue happen with only forge? The second one I mean.

**Comment by O13SC3N3** [comment]
With the same version it seemed to only happen with the cloak on and on an inferno mob of some types. We changed forge config to remove erroring entity and it hasn't happened since. We haven't updated to the latest botania yet.

**Comment by Vazkii** [comment]
I'll close for now, feel free to update if it still happens afterwards.
