### ISSUE TITLE
Pushing a livingrock near a pure daisy with a piston causes crash.

### ISSUE THREAD

**Issue by jrdroney** [Vazkii/Botania#772]
When we updated from .172 to .179 we thought it was the bore lens causing the crash, but after disabling the 'automatic livingrock farm' the player re-assembled it just to generate the livingrock (by pushing stone near a pure daisy), and it caused another crash as soon as it pushed the stone. I'm not sure what all you need, so I've included the crash log except system specs and modlist.

---- Minecraft Crash Report ----
// There are four lights!

Time: 4/18/15 8:57 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at vazkii.botania.api.recipe.RecipePureDaisy.isOreDict(RecipePureDaisy.java:52)
	at vazkii.botania.api.recipe.RecipePureDaisy.matches(RecipePureDaisy.java:45)
	at vazkii.botania.common.block.subtile.SubTilePureDaisy.onUpdate(SubTilePureDaisy.java:60)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_145845_h(TileSpecialFlower.java:92)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at vazkii.botania.api.recipe.RecipePureDaisy.isOreDict(RecipePureDaisy.java:52)
	at vazkii.botania.api.recipe.RecipePureDaisy.matches(RecipePureDaisy.java:45)
	at vazkii.botania.common.block.subtile.SubTilePureDaisy.onUpdate(SubTilePureDaisy.java:60)
	at vazkii.botania.common.block.tile.TileSpecialFlower.func_145845_h(TileSpecialFlower.java:92)

-- Block entity being ticked --
Details:
	Name: botania:specialFlower // vazkii.botania.common.block.tile.TileSpecialFlower
	Block type: ID #498 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-291,70,161), Chunk: (at 13,4,1 in -19,10; contains blocks -304,0,160 to -289,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #498 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Reckless
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 635 Drop: 0
	Level seed: -1359059433
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-216,64,196), Chunk: (at 8,4,4 in -14,12; contains blocks -224,0,192 to -209,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 40600945 game time, 10624 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10971 (now: false), thunder time: 77101 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jrdroney** [comment]
Apologies, we were on .171 and updated to .179, not .172.

**Comment by Vazkii** [comment]
I can't reproduce this, do you have cauldron?

**Comment by Vazkii** [comment]
Ok, I found out the issue. It never happens in vanilla, but under some circumstances it can break.
