### ISSUE TITLE
Crash with Lexica Botania

### ISSUE THREAD

**Issue by SanAndreasP** [Vazkii/Botania#809]
Minecraft 1.7.10
Botania r1.6-182
Forge 1.13.3.1389

I got the following crash while trying to view the Entry for the Rune of Fire while trying to craft a Munchdew (Munchdew -> Rune of Gluttony -> Rune of Fire).
It is reproducible, it is not an insta-crash for me, it takes a tiny bit (1-2 secs maybe?).

Here's the full crash log: https://gist.github.com/SanAndreasP/04b46a78ce358dc6257a
And here's the stacktrace if you don't want to scroll through the massive file:

<code>java.lang.NullPointerException: Rendering screen
	at vazkii.botania.common.lexicon.page.PageRecipe.renderItem(PageRecipe.java:159)
	at vazkii.botania.common.lexicon.page.PageRecipe.renderItemAtAngle(PageRecipe.java:117)
	at vazkii.botania.common.lexicon.page.PagePetalRecipe.renderRecipe(PagePetalRecipe.java:77)
	at vazkii.botania.common.lexicon.page.PageRecipe.renderScreen(PageRecipe.java:57)
	at vazkii.botania.client.gui.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:172)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)</code>

**Comment by Vazkii** [comment]
#802

**Comment by SanAndreasP** [comment]
Oh, you fixed it already. Good to know
